let wordList = [
  { russian: "я", chinese: "我", pinyin: "wǒ", category: "Местоимения" },
  { russian: "ты", chinese: "你", pinyin: "nǐ", category: "Местоимения" },
  { russian: "он", chinese: "他", pinyin: "tā", category: "Местоимения" },
  { russian: "она", chinese: "她", pinyin: "tā", category: "Местоимения" },
  { russian: "оно", chinese: "它", pinyin: "tā", category: "Местоимения" },
  {
    russian: "множ. число",
    chinese: "们",
    pinyin: "men",
    category: "Местоимения",
  },
  { russian: "мама", chinese: "妈妈", pinyin: "māma", category: "Семья" },
  { russian: "папа", chinese: "爸爸", pinyin: "bàba", category: "Семья" },
  { russian: "сын", chinese: "儿子", pinyin: "érzi", category: "Семья" },
  { russian: "дочь", chinese: "奴儿", pinyin: "nú'ér", category: "Семья" },
  {
    russian: "старший брат",
    chinese: "哥哥",
    pinyin: "gēge",
    category: "Семья",
  },
  {
    russian: "старшая сестра",
    chinese: "姐姐",
    pinyin: "jiějie",
    category: "Семья",
  },
  {
    russian: "младший брат",
    chinese: "弟弟",
    pinyin: "dìdi",
    category: "Семья",
  },
  {
    russian: "младшая сестра",
    chinese: "妹妹",
    pinyin: "mèimei",
    category: "Семья",
  },
  { russian: "дедушка", chinese: "爷爷", pinyin: "yéye", category: "Семья" },
  { russian: "бабушка", chinese: "奶奶", pinyin: "nǎinai", category: "Семья" },
  { russian: "семья", chinese: "家", pinyin: "jiā", category: "Семья" },
  { russian: "ребенок", chinese: "孩子", pinyin: "háizi", category: "Семья" },
  {
    russian: "парень",
    chinese: "男朋友",
    pinyin: "nán péngyǒu",
    category: "Семья",
  },
  {
    russian: "девушка",
    chinese: "奴朋友",
    pinyin: "nǔ péngyǒu",
    category: "Семья",
  },
  { russian: "друг", chinese: "朋友", pinyin: "péngyǒu", category: "Семья" },
  { russian: "собака", chinese: "狗", pinyin: "gǒu" },
  { russian: "кошка", chinese: "猫", pinyin: "māo" },
  { russian: "овца", chinese: "羊", pinyin: "yáng" },
  { russian: "корова", chinese: "牛", pinyin: "niú" },
  { russian: "свинья", chinese: "猪", pinyin: "zhū" },
  { russian: "рыба", chinese: "鱼", pinyin: "yú" },
  { russian: "птица", chinese: "鸟", pinyin: "niǎo" },
  { russian: "курица", chinese: "鸡", pinyin: "jī" },
  { russian: "панда", chinese: "熊猫", pinyin: "xióngmāo" },
  { russian: "кролик", chinese: "兔子", pinyin: "tùzi" },
  { russian: "Напитки", chinese: "饮料", pinyin: "yǐnliào" },
  { russian: "Чай", chinese: "茶", pinyin: "chá" },
  { russian: "Вода", chinese: "水", pinyin: "shuǐ" },
  { russian: "Кофе", chinese: "咖啡", pinyin: "kāfēi" },
  { russian: "Кола", chinese: "可乐", pinyin: "kělè" },
  { russian: "Алкоголь", chinese: "酒", pinyin: "jiǔ" },
  { russian: "Пиво", chinese: "啤酒", pinyin: "píjiǔ" },
  { russian: "Водка", chinese: "白酒", pinyin: "báijiǔ" },
  { russian: "Сок", chinese: "果汁", pinyin: "guǒzhī" },
  { russian: "Молоко", chinese: "牛奶", pinyin: "niúnǎi" },
  { russian: "Минеральная вода", chinese: "矿泉水", pinyin: "kuàngquán shuǐ" },
  { russian: "Свинина", chinese: "猪肉", pinyin: "zhūròu" },
  { russian: "Говядина", chinese: "牛肉", pinyin: "niúròu" },
  { russian: "Яйца", chinese: "鸡蛋", pinyin: "jīdàn" },
  { russian: "Хлеб", chinese: "面包", pinyin: "miànbāo" },
  { russian: "Овощи", chinese: "蔬菜", pinyin: "shūcài" },
  { russian: "Фрукты", chinese: "水果", pinyin: "shuǐguǒ" },
  { russian: "Торт", chinese: "蛋糕", pinyin: "dàngāo" },
  { russian: "Печенье", chinese: "饼干", pinyin: "bǐnggān" },
  { russian: "Яблоко", chinese: "苹果", pinyin: "píngguǒ" },
  { russian: "Манго", chinese: "芒果", pinyin: "mángguǒ" },
  { russian: "Ананас", chinese: "菠萝", pinyin: "bōluó" },
  { russian: "Арбуз", chinese: "西瓜", pinyin: "xīguā" },
  { russian: "Рис", chinese: "米饭", pinyin: "mǐfàn" },
  { russian: "Суп", chinese: "汤", pinyin: "tāng" },
  { russian: "Пельмени", chinese: "饺子", pinyin: "jiǎozi" },
  { russian: "Лапша", chinese: "面条", pinyin: "miàntiáo" },
  { russian: "Стейк", chinese: "牛排", pinyin: "niúpái" },
  { russian: "Салат", chinese: "沙拉", pinyin: "shālā" },
  { russian: "Лимон", chinese: "柠檬", pinyin: "níngméng" },
  { russian: "Гамбургер", chinese: "汉堡", pinyin: "hànbǎo" },
  { russian: "Картофель фри", chinese: "薯条", pinyin: "shǔtiáo" },
  { russian: "Огурец", chinese: "黄瓜", pinyin: "huángguā" },
  { russian: "Помидоры", chinese: "西红柿", pinyin: "xīhóngshì" },
  { russian: "Сельдерей", chinese: "芹菜", pinyin: "qíncài" },
  { russian: "Морковь", chinese: "胡萝卜", pinyin: "húluóbo" },
  { russian: "Банан", chinese: "香蕉", pinyin: "xiāngjiāo" },
  { russian: "Апельсин", chinese: "橙子", pinyin: "chéngzi" },
  { russian: "Клубника", chinese: "草莓", pinyin: "cǎoméi" },
  { russian: "Шоколад", chinese: "巧克力", pinyin: "qiǎokèlì" },
  { russian: "Мандарины", chinese: "橘子", pinyin: "júzi" },
  { russian: "Жареная утка", chinese: "烤鸭", pinyin: "kǎoyā" },
  { russian: "Основное блюдо", chinese: "主食", pinyin: "zhǔshí" },
  { russian: "Закуски", chinese: "小吃", pinyin: "xiǎochī" },
  { russian: "Быть", chinese: "是", pinyin: "shì" },
  { russian: "Иметь", chinese: "有", pinyin: "yǒu" },
  { russian: "Любить", chinese: "爱", pinyin: "ài" },
  { russian: "Нравиться", chinese: "喜欢", pinyin: "xǐhuān" },
  { russian: "Есть", chinese: "吃", pinyin: "chī" },
  { russian: "Есть еду", chinese: "吃饭", pinyin: "chīfàn" },
  { russian: "Пить", chinese: "喝", pinyin: "hē" },
  { russian: "Звать, называть", chinese: "叫", pinyin: "jiào" },
  { russian: "Говорить", chinese: "说", pinyin: "shuō" },
  { russian: "Разговаривать", chinese: "说话", pinyin: "shuōhuà" },
  { russian: "Разговаривать (неформ.)", chinese: "聊天", pinyin: "liáotiān" },
  { russian: "Учить", chinese: "学", pinyin: "xué" },
  { russian: "Изучать", chinese: "学习", pinyin: "xuéxí" },
  { russian: "Покупать", chinese: "买", pinyin: "mǎi" },
  { russian: "Продавать", chinese: "卖", pinyin: "mài" },
  { russian: "Хотеть", chinese: "想", pinyin: "xiǎng" },
  { russian: "Хотеть, нуждаться", chinese: "要", pinyin: "yào" },
  { russian: "Давать", chinese: "给", pinyin: "gěi" },
  { russian: "Идти", chinese: "去", pinyin: "qù" },
  { russian: "Находиться", chinese: "在", pinyin: "zài" },
  { russian: "Мыть", chinese: "洗", pinyin: "xǐ" },
  { russian: "Принимать душ, купаться", chinese: "洗澡", pinyin: "xǐzǎo" },
  { russian: "Умываться", chinese: "洗脸", pinyin: "xǐliǎn" },
  { russian: "Вставать с постели", chinese: "起床", pinyin: "qǐchuáng" },
  { russian: "Начинать работу", chinese: "上班", pinyin: "shàngbān" },
  { russian: "Заканчивать работу", chinese: "下班", pinyin: "xiàbān" },
  { russian: "Чистить зубы", chinese: "刷牙", pinyin: "shuāyá" },
  { russian: "Начинать учебу, занятие", chinese: "上课", pinyin: "shàngkè" },
  { russian: "Заказчивать учебу, занятие", chinese: "下课", pinyin: "xiàkè" },
  { russian: "Смотреть/читать", chinese: "看", pinyin: "kàn" },
  { russian: "Видеть", chinese: "看见", pinyin: "kànjiàn" },
  { russian: "Делать/готовить", chinese: "做", pinyin: "zuò" },
  { russian: "Готовить еду", chinese: "做饭", pinyin: "zuòfàn" },
  { russian: "Возвращаться", chinese: "回", pinyin: "huí" },
  { russian: "Приходить (куда-то)", chinese: "来", pinyin: "lái" },
  { russian: "Прибывать (куда-то)", chinese: "到", pinyin: "dào" },
  { russian: "Мочь, иметь возможность", chinese: "能", pinyin: "néng" },
  { russian: "Мочь, иметь возможность", chinese: "可以", pinyin: "kěyǐ" },
  { russian: "Спать", chinese: "睡觉", pinyin: "shuìjiào" },
  { russian: "Петь", chinese: "唱", pinyin: "chàng" },
  { russian: "Танцевать", chinese: "跳舞", pinyin: "tiàowǔ" },
  { russian: "Рисовать", chinese: "画画", pinyin: "huàhuà" },
  { russian: "Кататься на лыжах", chinese: "滑雪", pinyin: "huáxuě" },
  { russian: "Путешествовать", chinese: "旅游", pinyin: "lǚyóu" },
  { russian: "Открывать, включать", chinese: "开", pinyin: "kāi" },
  { russian: "Закрывать, выключать", chinese: "关", pinyin: "guān" },
  { russian: "Помогать", chinese: "帮", pinyin: "bāng" },
  { russian: "Ждать", chinese: "等", pinyin: "děng" },
  { russian: "Искать", chinese: "找", pinyin: "zhǎo" },
  { russian: "Сталкиваться (с кем-то)", chinese: "遇到", pinyin: "yùdào" },
  { russian: "Заканчиваться", chinese: "结束", pinyin: "jiéshù" },
  { russian: "Опаздывать", chinese: "迟到", pinyin: "chídào" },
  { russian: "Начинаться", chinese: "开始", pinyin: "kāishǐ" },
  { russian: "Убираться, чистить", chinese: "打扫", pinyin: "dǎsǎo" },
  { russian: "Слушать", chinese: "听", pinyin: "tīng" },
  { russian: "Слушаться", chinese: "听话", pinyin: "tīnghuà" },
  { russian: "Играть", chinese: "玩", pinyin: "wán" },
  { russian: "Сделать и получить результат", chinese: "完", pinyin: "wán" },
  { russian: "Серфить в интернете", chinese: "上网", pinyin: "shàngwǎng" },
  {
    russian: "Надевать, носить (пальто, рубашку …)",
    chinese: "穿",
    pinyin: "chuān",
  },
  {
    russian: "Надевать, носить (шапку, очки, перчатки)",
    chinese: "戴",
    pinyin: "dài",
  },
  { russian: "Думать, полагать", chinese: "觉得", pinyin: "juédé" },
  { russian: "Примерять (одежду)", chinese: "试", pinyin: "shì" },
  { russian: "Попробовать (еду)", chinese: "尝", pinyin: "cháng" },
  { russian: "Забронировать", chinese: "预订", pinyin: "yùdìng" },
  { russian: "Использовать", chinese: "用", pinyin: "yòng" },
  { russian: "Звонить", chinese: "打", pinyin: "dǎ" },
  { russian: "Играть (в спорт руками)", chinese: "打", pinyin: "dǎ" },
  {
    russian: "Уметь (иметь приобретенный навык)",
    chinese: "会",
    pinyin: "huì",
  },
  { russian: "Пинать (мяч)", chinese: "踢", pinyin: "tī" },
  { russian: "Кататься", chinese: "骑", pinyin: "qí" },
  { russian: "Бегать", chinese: "跑步", pinyin: "pǎobù" },
  { russian: "Гулять", chinese: "散步", pinyin: "sànbù" },
  { russian: "Идти пешком", chinese: "走路", pinyin: "zǒulù" },
  { russian: "Прогуливаться", chinese: "逛", pinyin: "guàng" },
  { russian: "Плавать", chinese: "游泳", pinyin: "yóuyǒng" },
  { russian: "Следует (должно, нужно)", chinese: "应该", pinyin: "yīnggāi" },
  { russian: "Требуется", chinese: "需要", pinyin: "xūyào" },
  { russian: "Не спать всю ночь", chinese: "熬夜", pinyin: "áoyè" },
  { russian: "Ругаться", chinese: "吵架", pinyin: "chǎojià" },
  { russian: "Расставаться", chinese: "分手", pinyin: "fēnshǒu" },
  { russian: "Жениться", chinese: "结婚", pinyin: "jiéhūn" },
  { russian: "Встретиться", chinese: "见面", pinyin: "jiànmiàn" },
  { russian: "Пригласить, позаботиться", chinese: "请", pinyin: "qǐng" },
  { russian: "Проводить, довезти", chinese: "送", pinyin: "sòng" },
  { russian: "Дарить", chinese: "送", pinyin: "sòng" },
  { russian: "Работать", chinese: "工作", pinyin: "gōngzuò" },
  { russian: "Стать (кем-то)", chinese: "当", pinyin: "dāng" },
  { russian: "Приносить", chinese: "拿", pinyin: "ná" },
  { russian: "Совещаться", chinese: "开会", pinyin: "kāihuì" },
  { russian: "Быть в командировке", chinese: "出差", pinyin: "chūchāi" },
  { russian: "Распечатывать, печатать", chinese: "打印", pinyin: "dǎyìn" },
  { russian: "Ксерить", chinese: "复印", pinyin: "fùyìn" },
  { russian: "Сидеть (ехать в транспорте)", chinese: "坐", pinyin: "zuò" },
  { russian: "Вести машину", chinese: "开车", pinyin: "kāichē" },
  { russian: "Отправлять", chinese: "发", pinyin: "fā" },
  { russian: "Отвечать на звонок", chinese: "接", pinyin: "jiē" },
  { russian: "Получать (сообщение)", chinese: "收", pinyin: "shōu" },
  { russian: "Испытывать боль", chinese: "疼", pinyin: "téng" },
  { russian: "Простужаться", chinese: "感冒", pinyin: "gǎnmào" },
  { russian: "Температурить", chinese: "发烧", pinyin: "fāshāo" },
  { russian: "Болеть", chinese: "病", pinyin: "bìng" },
  { russian: "Болеть", chinese: "生病", pinyin: "shēngbìng" },
  { russian: "Отдыхать", chinese: "休息", pinyin: "xiūxí" },
  { russian: "Класть", chinese: "放", pinyin: "fàng" },
  { russian: "Сделать что-то", chinese: "弄", pinyin: "nòng" },
  { russian: "Портить", chinese: "坏", pinyin: "huài" },
  { russian: "Терять", chinese: "丢", pinyin: "diū" },
  { russian: "Знать (что-то)", chinese: "知道", pinyin: "zhīdào" },
  { russian: "Знать (кого-то)", chinese: "认识", pinyin: "rènshì" },
  { russian: "Ругать", chinese: "骂", pinyin: "mà" },
  { russian: "Красть", chinese: "偷", pinyin: "tōu" },
  { russian: "Врать", chinese: "骗", pinyin: "piàn" },
  { russian: "Растить, иметь животное", chinese: "养", pinyin: "yǎng" },
  { russian: "Решиться, дерзнуть", chinese: "敢", pinyin: "gǎn" },
  { russian: "Гладить (животное)", chinese: "摸", pinyin: "mō" },
  { russian: "Выходить из дома", chinese: "出门", pinyin: "chūmén" },
  { russian: "Составлять компанию", chinese: "陪", pinyin: "péi" },
  { russian: "Кашлять", chinese: "咳嗽", pinyin: "késòu" },
  { russian: "Давать разрешение, велеть", chinese: "让", pinyin: "ràng" },
  { russian: "Делать укол", chinese: "打针", pinyin: "dǎzhēn" },
  { russian: "Госпитализировать", chinese: "住院", pinyin: "zhùyuàn" },
  { russian: "Заказывать (в ресторане)", chinese: "点菜", pinyin: "diǎncài" },
  {
    russian: "Оплачивать счет (в ресторане)",
    chinese: "买单",
    pinyin: "mǎidān",
  },
  { russian: "Забрать остатки", chinese: "打包", pinyin: "dǎbāo" },
  { russian: "Повернуть", chinese: "拐", pinyin: "guǎi" },
  {
    russian: "Тренироваться (заниматься фитнесом)",
    chinese: "健身",
    pinyin: "jiànshēn",
  },
  { russian: "Штука (общее сч.слово)", chinese: "个", pinyin: "gè" },
  { russian: "Раз (к действиям)", chinese: "次", pinyin: "cì" },
  { russian: "Раз (к перемещениям)", chinese: "趟", pinyin: "tàng" },
  { russian: "Раз (к завершенным действиям)", chinese: "遍", pinyin: "biàn" },
  { russian: "Вид", chinese: "种", pinyin: "zhǒng" },
  { russian: "К порядковым числительным", chinese: "第", pinyin: "dì" },
  { russian: "Слайс (кусочек хлеба, и т.д.)", chinese: "片", pinyin: "piàn" },
  { russian: "Денежная единица", chinese: "块", pinyin: "kuài" },
  { russian: "К длинным тонким предметам", chinese: "支", pinyin: "zhī" },
  { russian: "К плоским предметам", chinese: "张", pinyin: "zhāng" },
  { russian: "К технике", chinese: "部", pinyin: "bù" },
  { russian: "К технике", chinese: "台", pinyin: "tái" },
  { russian: "Пакет (молока и т.п.)", chinese: "袋", pinyin: "dài" },
  { russian: "Коробка (молока и т.п.)", chinese: "盒", pinyin: "hé" },
  { russian: "К животным (кошка, собака)", chinese: "只", pinyin: "zhī" },
  { russian: "Годик", chinese: "岁", pinyin: "suì" },
  { russian: "Стакан", chinese: "杯", pinyin: "bēi" },
  { russian: "Плошка", chinese: "碗", pinyin: "wǎn" },
  { russian: "Тарелка", chinese: "盘", pinyin: "pán" },
  { russian: "Кусок (торта)", chinese: "块", pinyin: "kuài" },
  { russian: "Бутылка", chinese: "瓶", pinyin: "píng" },
  { russian: "К членам семьи", chinese: "口", pinyin: "kǒu" },
  { russian: "Пара", chinese: "双", pinyin: "shuāng" },
  { russian: "Блюдо", chinese: "菜", pinyin: "cài" },
  { russian: "К документам", chinese: "份", pinyin: "fèn" },
  { russian: "К вещам (пальто, рубашка)", chinese: "件", pinyin: "jiàn" },
  {
    russian: "К длинным предметам (штаны, дороги, реки)",
    chinese: "条",
    pinyin: "tiáo",
  },
  { russian: "Килограмм", chinese: "公斤", pinyin: "gōngjīn" },
  { russian: "Полкило", chinese: "斤", pinyin: "jīn" },
  { russian: "К книгам", chinese: "本", pinyin: "běn" },
  { russian: "Чашка", chinese: "杯子", pinyin: "bēizi" },
  { russian: "Вилка", chinese: "叉子", pinyin: "chāzi" },
  { russian: "Ложка", chinese: "勺子", pinyin: "sháozi" },
  { russian: "Палочки", chinese: "筷子", pinyin: "kuàizi" },
  { russian: "Время", chinese: "时间", pinyin: "shíjiān" },
  { russian: "Час (который час)", chinese: "点", pinyin: "diǎn" },
  { russian: "Минута (который час)", chinese: "分", pinyin: "fēn" },
  { russian: "Час (астрономический)", chinese: "小时", pinyin: "xiǎoshí" },
  { russian: "Минута (астрономическая)", chinese: "分钟", pinyin: "fēnzhōng" },
  { russian: "Раннее утро", chinese: "早上", pinyin: "zǎoshàng" },
  { russian: "Первая половина дня", chinese: "上午", pinyin: "shàngwǔ" },
  { russian: "Полдень", chinese: "中午", pinyin: "zhōngwǔ" },
  { russian: "Вторая половина дня", chinese: "下午", pinyin: "xiàwǔ" },
  { russian: "Вечер, ночь", chinese: "晚上", pinyin: "wǎnshàng" },
  { russian: "Сейчас", chinese: "现在", pinyin: "xiànzài" },
  { russian: "До, перед (по времени)", chinese: "以前", pinyin: "yǐqián" },
  { russian: "После (по времени)", chinese: "以后", pinyin: "yǐhòu" },
  { russian: "Завтрак", chinese: "早饭", pinyin: "zǎofàn" },
  { russian: "Обед", chinese: "午饭", pinyin: "wǔfàn" },
  { russian: "Ужин", chinese: "晚饭", pinyin: "wǎnfàn" },
  { russian: "Неделя", chinese: "星期", pinyin: "xīngqī" },
  { russian: "Понедельник", chinese: "星期一", pinyin: "xīngqīyī" },
  { russian: "Вторник", chinese: "星期二", pinyin: "xīngqī'èr" },
  { russian: "Среда", chinese: "星期三", pinyin: "xīngqīsān" },
  { russian: "Четверг", chinese: "星期四", pinyin: "xīngqīsì" },
  { russian: "Пятница", chinese: "星期五", pinyin: "xīngqīwǔ" },
  { russian: "Суббота", chinese: "星期六", pinyin: "xīngqīliù" },
  { russian: "Воскресенье", chinese: "星期天", pinyin: "xīngqītiān" },
  { russian: "Сегодня", chinese: "今天", pinyin: "jīntiān" },
  { russian: "Завтра", chinese: "明天", pinyin: "míngtiān" },
  { russian: "Вчера", chinese: "昨天", pinyin: "zuótiān" },
  { russian: "Год", chinese: "年", pinyin: "nián" },
  { russian: "Месяц", chinese: "月", pinyin: "yuè" },
  { russian: "День (месяца)", chinese: "号", pinyin: "hào" },
  { russian: "День рождения", chinese: "生日", pinyin: "shēngrì" },
  { russian: "Каждый день", chinese: "每天", pinyin: "měitiān" },
  { russian: "Выходные", chinese: "周末", pinyin: "zhōumò" },
  { russian: "Ресторан", chinese: "饭馆", pinyin: "fànguǎn" },
  { russian: "Парк", chinese: "公园", pinyin: "gōngyuán" },
  { russian: "Школа, учебное заведение", chinese: "学校", pinyin: "xuéxiào" },
  { russian: "Банк", chinese: "银行", pinyin: "yínháng" },
  { russian: "Супермаркет", chinese: "超市", pinyin: "chāoshì" },
  { russian: "Магазин", chinese: "商店", pinyin: "shāngdiàn" },
  { russian: "Аэропорт", chinese: "机场", pinyin: "jīchǎng" },
  { russian: "Больница", chinese: "医院", pinyin: "yīyuàn" },
  { russian: "Офис", chinese: "办公室", pinyin: "bàngōngshì" },
  { russian: "Компания", chinese: "公司", pinyin: "gōngsī" },
  { russian: "Отель", chinese: "酒店", pinyin: "jiǔdiàn" },
  { russian: "Пекарня", chinese: "面包店", pinyin: "miànbāodiàn" },
  { russian: "Кафе", chinese: "咖啡馆", pinyin: "kāfēiguǎn" },
  { russian: "Автозаправка", chinese: "加油站", pinyin: "jiāyóuzhàn" },
  { russian: "Зоопарк", chinese: "动物园", pinyin: "dòngwùyuán" },
  { russian: "Парковка", chinese: "停车场", pinyin: "tíngchēchǎng" },
  { russian: "Великая Китайская Стена", chinese: "长城", pinyin: "chángchéng" },
  { russian: "Учебный корпус", chinese: "教学楼", pinyin: "jiàoxuélóu" },
  { russian: "Общага", chinese: "宿舍", pinyin: "sùshè" },
  { russian: "Спортивная площадка", chinese: "运动场", pinyin: "yùndòngchǎng" },
  { russian: "Спортзал", chinese: "体育馆", pinyin: "tǐyùguǎn" },
  { russian: "Библиотека", chinese: "图书馆", pinyin: "túshūguǎn" },
  { russian: "Книжный магазин", chinese: "书店", pinyin: "shūdiàn" },
  { russian: "Тренажерный зал", chinese: "健身房", pinyin: "jiànshēnfáng" },
  { russian: "Туалет", chinese: "厕所", pinyin: "cèsuǒ" },
  { russian: "Почта", chinese: "邮局", pinyin: "yóujú" },
  { russian: "Лето", chinese: "夏天", pinyin: "xiàtiān" },
  { russian: "Осень", chinese: "秋天", pinyin: "qiūtiān" },
  { russian: "Весна", chinese: "春天", pinyin: "chūntiān" },
  { russian: "Зима", chinese: "冬天", pinyin: "dōngtiān" },
  { russian: "Ветренно", chinese: "刮风", pinyin: "guāfēng" },
  { russian: "Идет снег", chinese: "下雪", pinyin: "xiàxuě" },
  { russian: "Идет дождь", chinese: "下雨", pinyin: "xiàyǔ" },
  { russian: "Солнечно", chinese: "晴天", pinyin: "qíngtiān" },
  { russian: "Пасмурно", chinese: "阴天", pinyin: "yīntiān" },
  { russian: "Погода", chinese: "天气", pinyin: "tiānqì" },
  { russian: "Прохладно", chinese: "凉快", pinyin: "liángkuài" },
  { russian: "Тепло", chinese: "暖和", pinyin: "nuǎnhuo" },
  { russian: "Спереди", chinese: "前边", pinyin: "qiánbiān" },
  { russian: "Сзади", chinese: "后边", pinyin: "hòubiān" },
  { russian: "Рядом", chinese: "附近", pinyin: "fùjìn" },
  { russian: "На, над", chinese: "上边", pinyin: "shàngbiān" },
  { russian: "Под", chinese: "下边", pinyin: "xiàbiān" },
  { russian: "Север", chinese: "北边", pinyin: "běibiān" },
  { russian: "Юг", chinese: "南边", pinyin: "nánbiān" },
  { russian: "Запад", chinese: "西边", pinyin: "xībiān" },
  { russian: "Восток", chinese: "东边", pinyin: "dōngbiān" },
  { russian: "Внутри", chinese: "里边", pinyin: "lǐbiān" },
  { russian: "Снаружи", chinese: "外边", pinyin: "wàibiān" },
  { russian: "Напротив", chinese: "对面", pinyin: "duìmiàn" },
  { russian: "Рядом", chinese: "旁边", pinyin: "pángbiān" },
  { russian: "Слева", chinese: "左边", pinyin: "zuǒbiān" },
  { russian: "Справа", chinese: "右边", pinyin: "yòubiān" },
  { russian: "С обеих сторон", chinese: "两边", pinyin: "liǎngbiān" },
  { russian: "Посередине", chinese: "中间", pinyin: "zhōngjiān" },
  {
    russian: "От (что-то от чего-то о местонахождении)",
    chinese: "离",
    pinyin: "lí",
  },
  { russian: "Далеко", chinese: "远", pinyin: "yuǎn" },
  { russian: "Близко", chinese: "近", pinyin: "jìn" },
  { russian: "К (указание направление)", chinese: "向", pinyin: "xiàng" },
  {
    russian: "Строго (указание направления)",
    chinese: "一直",
    pinyin: "yìzhí",
  },
  { russian: "Вдоль (дороги)", chinese: "沿", pinyin: "yán" },
  { russian: "К (указание направления)", chinese: "往", pinyin: "wǎng" },
  { russian: "с(от)…до(по)", chinese: "从。。。到", pinyin: "cóng... dào" },
  { russian: "Здесь", chinese: "这里", pinyin: "zhèlǐ" },
  { russian: "Там", chinese: "哪里", pinyin: "nǎlǐ" },
  { russian: "Фамилия", chinese: "姓", pinyin: "xìng" },
  { russian: "Имя", chinese: "名字", pinyin: "míngzi" },
  { russian: "Мистер", chinese: "先生", pinyin: "xiānsheng" },
  { russian: "Мадам", chinese: "女士", pinyin: "nǚshì" },
  { russian: "Учитель", chinese: "老师", pinyin: "lǎoshī" },
  { russian: "Ученик", chinese: "学生", pinyin: "xuéshēng" },
  { russian: "Врач", chinese: "医生", pinyin: "yīshēng" },
  { russian: "Официант", chinese: "服务员", pinyin: "fúwùyuán" },
  { russian: "Соученик", chinese: "同学", pinyin: "tóngxué" },
  { russian: "Коллега", chinese: "同事", pinyin: "tóngshì" },
  { russian: "Инженер", chinese: "工程师", pinyin: "gōngchéngshī" },
  { russian: "Офисный работник", chinese: "职员", pinyin: "zhíyuán" },
  { russian: "Водитель", chinese: "司机", pinyin: "sījī" },
  { russian: "Полицейский", chinese: "警察", pinyin: "jǐngchá" },
  { russian: "Юрист", chinese: "律师", pinyin: "lǜshī" },
  { russian: "Актер", chinese: "演员", pinyin: "yǎnyuán" },
  { russian: "Клиент", chinese: "客户", pinyin: "kèhù" },
  { russian: "Начальник", chinese: "老板", pinyin: "lǎobǎn" },
  { russian: "Консультант", chinese: "营业员", pinyin: "yíngyèyuán" },
  { russian: "Наличные", chinese: "现金", pinyin: "xiànjīn" },
  { russian: "Кредитка", chinese: "信用卡", pinyin: "xìnyòngkǎ" },
  { russian: "Алипей", chinese: "支付宝", pinyin: "zhīfùbǎo" },
  { russian: "Деньги", chinese: "钱", pinyin: "qián" },
  { russian: "Денежная единица", chinese: "块", pinyin: "kuài" },
  { russian: "10 феней", chinese: "毛", pinyin: "máo" },
  { russian: "Китайская копейка", chinese: "分", pinyin: "fēn" },
  { russian: "Одежда", chinese: "衣服", pinyin: "Yifu" },
  { russian: "Ботинки", chinese: "鞋子", pinyin: "Xiezi" },
  { russian: "Штаны", chinese: "裤子", pinyin: "Kuzi" },
  { russian: "Платье, юбка", chinese: "裙子", pinyin: "Qunzi" },
  { russian: "Рубашка", chinese: "衬衫", pinyin: "Chenshan" },
  { russian: "Пальто", chinese: "外套", pinyin: "Waitao" },
  { russian: "Шапка, шляпа", chinese: "帽子", pinyin: "Maozi" },
  { russian: "Шарф", chinese: "围巾", pinyin: "Weijin" },
  { russian: "Свитер", chinese: "毛衣", pinyin: "Maoyi" },
  { russian: "Носки", chinese: "袜子", pinyin: "Wazi" },
  { russian: "Лицо", chinese: "脸", pinyin: "liǎn" },
  { russian: "Голова", chinese: "头", pinyin: "tóu" },
  { russian: "Волосы", chinese: "头发", pinyin: "tóufa" },
  { russian: "Глаза", chinese: "眼睛", pinyin: "yǎnjīng" },
  { russian: "Нос", chinese: "鼻子", pinyin: "bízi" },
  { russian: "Ноги", chinese: "腿", pinyin: "tuǐ" },
  { russian: "Рот", chinese: "嘴", pinyin: "zuǐ" },
  { russian: "Уши", chinese: "耳朵", pinyin: "ěrduǒ" },
  { russian: "Живот", chinese: "肚子", pinyin: "dùzi" },
  { russian: "Зубы", chinese: "牙", pinyin: "yá" },
  { russian: "Руки", chinese: "手", pinyin: "shǒu" },
  { russian: "Цвет", chinese: "颜色", pinyin: "yánsè" },
  { russian: "Синий", chinese: "蓝色", pinyin: "lán sè" },
  { russian: "Красный", chinese: "红色", pinyin: "hóng sè" },
  { russian: "Желтый", chinese: "黄色", pinyin: "huáng sè" },
  { russian: "Белый", chinese: "白色", pinyin: "bái sè" },
  { russian: "Черный", chinese: "黑色", pinyin: "hēi sè" },
  { russian: "Золотой", chinese: "金色", pinyin: "jīn sè" },
  { russian: "Коричневый", chinese: "棕色", pinyin: "zōng sè" },
  { russian: "Розовый", chinese: "粉色", pinyin: "fěn sè" },
  { russian: "Баскетбол", chinese: "篮球", pinyin: "lánqiú" },
  { russian: "Волейбол", chinese: "排球", pinyin: "páiqiú" },
  { russian: "Пингпонг", chinese: "乒乓球", pinyin: "pīngpāngqiú" },
  { russian: "Теннис", chinese: "网球", pinyin: "wǎngqiú" },
  { russian: "Футбол", chinese: "足球", pinyin: "zúqiú" },
  { russian: "Бейсбол", chinese: "棒球", pinyin: "bàngqiú" },
  { russian: "Бадминтон", chinese: "羽毛球", pinyin: "yǔmáoqiú" },
  { russian: "Велосипед", chinese: "自行车", pinyin: "zìxíngchē" },
  { russian: "Мотоцикл", chinese: "摩托车", pinyin: "mótuōchē" },
  { russian: "Самолет", chinese: "飞机", pinyin: "fēijī" },
  { russian: "Поезд", chinese: "火车", pinyin: "huǒchē" },
  { russian: "Лодка", chinese: "船", pinyin: "chuán" },
  { russian: "Такси", chinese: "出租车", pinyin: "chūzūchē" },
  { russian: "Метро", chinese: "地铁", pinyin: "dìtiě" },
  { russian: "Автобус", chinese: "公交车", pinyin: "Gongjiaoche" },
  { russian: "Стол", chinese: "桌子", pinyin: "Zhuozi" },
  { russian: "Кровать", chinese: "床", pinyin: "Chuang" },
  { russian: "Книга", chinese: "书", pinyin: "Shu" },
  { russian: "Телевизор", chinese: "电视", pinyin: "Dianshi" },
  { russian: "Фильм", chinese: "电影", pinyin: "Dianying" },
  { russian: "Музыка", chinese: "音乐", pinyin: "Yinyue" },
  { russian: "Игра", chinese: "游戏", pinyin: "Youxi" },
  { russian: "Газета", chinese: "报纸", pinyin: "Baozhi" },
  { russian: "Мобильник", chinese: "手机", pinyin: "Shouji" },
  { russian: "Часы наручные", chinese: "手表", pinyin: "Shoubiao" },
  { russian: "Сумка", chinese: "包", pinyin: "Bao" },
  { russian: "Школьный рюкзак", chinese: "书包", pinyin: "Shubao" },
  { russian: "Очки", chinese: "眼镜", pinyin: "Yanjing" },
  { russian: "Цветы", chinese: "花", pinyin: "Hua" },
  { russian: "Лампа, свет", chinese: "灯", pinyin: "Deng" },
  { russian: "Компьютер", chinese: "电脑", pinyin: "Diannao" },
  { russian: "Кошелек", chinese: "钱包", pinyin: "Qianbao" },
  { russian: "Песня", chinese: "哥", pinyin: "Ge" },
  { russian: "Дорога", chinese: "路", pinyin: "Lu" },
  { russian: "Перекресток", chinese: "路口", pinyin: "Lukou" },
  { russian: "Домашняя работа", chinese: "作业", pinyin: "Zuoye" },
  { russian: "Письмо", chinese: "信", pinyin: "Xin" },
  { russian: "Билет", chinese: "票", pinyin: "Piao" },
  { russian: "Станция", chinese: "站", pinyin: "Zhan" },
  { russian: "Лекарство", chinese: "药", pinyin: "Yao" },
  { russian: "Договор", chinese: "合同", pinyin: "Hetong" },
  { russian: "Документ", chinese: "文件", pinyin: "Wenjian" },
  { russian: "Ручка", chinese: "比", pinyin: "Bi" },
  { russian: "Визитка", chinese: "名片", pinyin: "Mingpian" },
  { russian: "Пекинская опера", chinese: "京剧", pinyin: "Jingju" },
  { russian: "Каллиграфия", chinese: "书法", pinyin: "Shufa" },
  { russian: "Подарок", chinese: "礼物", pinyin: "Liwu" },
  { russian: "Дверь", chinese: "门", pinyin: "Men" },
  { russian: "Телефон", chinese: "电话", pinyin: "Dianhua" },
  { russian: "Словарь", chinese: "词典", pinyin: "Cidian" },
  { russian: "Комната", chinese: "房间", pinyin: "Fangjian" },
  { russian: "Спальня", chinese: "卧室", pinyin: "Woshi" },
  { russian: "Кухня", chinese: "厨房", pinyin: "Chufang" },
  { russian: "Ванная комната", chinese: "卫生间", pinyin: "Weishengjian" },
  { russian: "Гостиная", chinese: "客厅", pinyin: "Keting" },
  { russian: "Стул", chinese: "椅子", pinyin: "Yizi" },
  { russian: "Холодильник", chinese: "冰箱", pinyin: "Bingxiang" },
  { russian: "Шкаф", chinese: "柜子", pinyin: "Guizi" },
  { russian: "Фотография", chinese: "照片", pinyin: "Zhaopian" },
  { russian: "Стена", chinese: "墙", pinyin: "Qiang" },
  { russian: "Смска", chinese: "短信", pinyin: "Duanxin" },
  { russian: "Электронное сообщение", chinese: "邮件", pinyin: "Youjian" },
  { russian: "Вичат", chinese: "微信", pinyin: "Weixin" },
  { russian: "Всякое разное", chinese: "东西", pinyin: "Dongxi" },
  { russian: "Иероглифы", chinese: "汉字", pinyin: "Hanzi" },
  { russian: "Лифт", chinese: "电梯", pinyin: "Dianti" },
  { russian: "Меню", chinese: "菜单", pinyin: "Caidan" },
  { russian: "Манеры, отношение", chinese: "态度", pinyin: "Taidu" },
  { russian: "Вкус", chinese: "味道", pinyin: "Weidao" },
  { russian: "Хороший", chinese: "好", pinyin: "Hao" },
  { russian: "Плохой", chinese: "差", pinyin: "Cha" },
  { russian: "Большой", chinese: "大", pinyin: "Da" },
  { russian: "Маленький", chinese: "小", pinyin: "Xiao" },
  { russian: "Дорогой", chinese: "贵", pinyin: "Gui" },
  { russian: "Дешевый", chinese: "便宜", pinyin: "Pianyi" },
  { russian: "Холодный", chinese: "冷", pinyin: "Leng" },
  { russian: "Горячий", chinese: "热", pinyin: "Re" },
  { russian: "Голодный", chinese: "饿", pinyin: "E" },
  { russian: "Испытывающий жажду", chinese: "渴", pinyin: "Ke" },
  { russian: "Вкусный о еде", chinese: "好吃", pinyin: "Haochi" },
  { russian: "Вкусный о питье", chinese: "好喝", pinyin: "Haohe" },
  { russian: "Красивый", chinese: "好看", pinyin: "Haokan" },
  { russian: "Чистый", chinese: "干净", pinyin: "Ganjing" },
  { russian: "Прекрасный", chinese: "漂亮", pinyin: "Piaoliang" },
  { russian: "Новый", chinese: "新", pinyin: "Xin" },
  { russian: "Старый", chinese: "旧", pinyin: "Jiu" },
  { russian: "Тесный (толпа)", chinese: "挤", pinyin: "Ji" },
  { russian: "Удобный, подходящий", chinese: "方便", pinyin: "Fangbian" },
  { russian: "Хорошо себя чувствующий", chinese: "舒服", pinyin: "Shufu" },
  { russian: "Занятый", chinese: "忙", pinyin: "Mang" },
  { russian: "Уставший", chinese: "累", pinyin: "Lei" },
  { russian: "Бедный", chinese: "穷", pinyin: "Qiong" },
  { russian: "Свободный", chinese: "轻松", pinyin: "Qingsong" },
  { russian: "Богатый", chinese: "有钱", pinyin: "Youqian" },
  { russian: "Странный", chinese: "奇怪", pinyin: "Qiguai" },
  { russian: "Интересный", chinese: "有意思", pinyin: "Youyisi" },
  { russian: "Сладкий", chinese: "甜", pinyin: "Tian" },
  { russian: "Горький", chinese: "苦", pinyin: "Ku" },
  { russian: "Кислый", chinese: "酸", pinyin: "Suan" },
  { russian: "Соленый", chinese: "咸", pinyin: "Xian" },
  { russian: "Острый", chinese: "辣", pinyin: "La" },
  { russian: "Длинный", chinese: "长", pinyin: "Chang" },
  { russian: "Короткий", chinese: "短", pinyin: "Duan" },
  { russian: "Высокий", chinese: "高", pinyin: "Gao" },
  { russian: "Низкий", chinese: "矮", pinyin: "Ai" },
  { russian: "Толстый", chinese: "胖", pinyin: "Pang" },
  { russian: "Худой", chinese: "瘦", pinyin: "Shou" },
  { russian: "Классный", chinese: "帅", pinyin: "Shuai" },
  { russian: "Милый", chinese: "可爱", pinyin: "Keai" },
  { russian: "Умный", chinese: "聪明", pinyin: "Congming" },
  { russian: "Свежий", chinese: "新鲜", pinyin: "Xinxian" },
  { russian: "Грязный", chinese: "脏", pinyin: "Zang" },
  { russian: "Послушный", chinese: "听话", pinyin: "Tinghua" },
  { russian: "Хороший (о животном)", chinese: "乖", pinyin: "Guai" },
  { russian: "Ленивый", chinese: "懒", pinyin: "Lan" },
  { russian: "Глупый", chinese: "傻", pinyin: "Sha" },
  { russian: "Уродливый", chinese: "丑", pinyin: "Chou" },
  { russian: "Сонный", chinese: "困", pinyin: "Kun" },
  { russian: "Сытый", chinese: "饱", pinyin: "Bao" },
  { russian: "Известный", chinese: "有名", pinyin: "Youming" },
  { russian: "Горячий (кипящий)", chinese: "烫", pinyin: "Tang" },
  { russian: "Оживленный", chinese: "热闹", pinyin: "Renao" },
  { russian: "Страдающий", chinese: "伤心", pinyin: "Shangxin" },
  { russian: "Испуганный", chinese: "害怕", pinyin: "Haipa" },
  { russian: "Переживающий", chinese: "担心", pinyin: "Danxin" },
  { russian: "Тоскующий", chinese: "郁闷", pinyin: "Yumen" },
  { russian: "Грустый", chinese: "难过", pinyin: "Nanguo" },
  { russian: "Веселый", chinese: "高兴", pinyin: "Gaoxing" },
  { russian: "Часто", chinese: "常常", pinyin: "Changchang" },
  { russian: "Часто", chinese: "经常", pinyin: "Jingchang" },
  { russian: "Сразу же", chinese: "马上", pinyin: "Mashang" },
  { russian: "Очень", chinese: "很", pinyin: "Hen" },
  { russian: "Чрезвычайно", chinese: "非常", pinyin: "Feichang" },
  { russian: "Особенно", chinese: "特别", pinyin: "Tebie" },
  { russian: "Так (слишком)", chinese: "太…了", pinyin: "Tai…le" },
  { russian: "Реально, действительно", chinese: "真", pinyin: "Zhen" },
  { russian: "Немного", chinese: "有点儿", pinyin: "Youdianr" },
  { russian: "Немного", chinese: "一点儿", pinyin: "Yidianr" },
  { russian: "Обычно", chinese: "平时", pinyin: "Pingshi" },
  { russian: "Всегда", chinese: "一直", pinyin: "Yizhi" },
  { russian: "Быстро", chinese: "快", pinyin: "Kuai" },
  { russian: "Медленно", chinese: "慢", pinyin: "Man" },
  { russian: "Рано", chinese: "早", pinyin: "Zao" },
  { russian: "Поздно", chinese: "晚", pinyin: "Wan" },
  { russian: "Уже", chinese: "已经", pinyin: "Yijing" },
  { russian: "Только что", chinese: "刚才", pinyin: "Gangcai" },
  { russian: "Одновременно", chinese: "一边", pinyin: "Yibian" },
  { russian: "Иногда", chinese: "有时候", pinyin: "Youshihou" },
  { russian: "В то время как", chinese: "的时候", pinyin: "Deshihou" },
  {
    russian: "Несколько (немного) времени",
    chinese: "一会儿",
    pinyin: "Yihuir",
  },
  { russian: "Несколько (немного) о количестве", chinese: "几", pinyin: "ji" },
  {
    russian: "Сравнительная степень (что-то) чем (что-то)",
    chinese: "比",
    pinyin: "Bi",
  },
  {
    russian: "Сравнительная степень (не такой как)",
    chinese: "没有",
    pinyin: "Meiyou",
  },
  {
    russian: "Сравнительная степень (еще более…)",
    chinese: "更",
    pinyin: "Geng",
  },
  { russian: "Самый", chinese: "最", pinyin: "Zui" },
  { russian: "Такое же", chinese: "一样", pinyin: "Yiyang" },
  { russian: "Все более и более", chinese: "越来越", pinyin: "Yuelauyue" },
  { russian: "Не (настоящее и будущее)", chinese: "不", pinyin: "Bu" },
  {
    russian: "Не (прошедшее и продолжающееся, с глаголом “иметь”)",
    chinese: "没",
    pinyin: "Mei",
  },
  { russian: "Это", chinese: "这", pinyin: "Zhe" },
  { russian: "То", chinese: "那", pinyin: "Na" },
  { russian: "Тоже", chinese: "也", pinyin: "Ye" },
  { russian: "Все, оба", chinese: "都", pinyin: "Dou" },
  {
    russian: "Частица принадлежности, утвердительная форма",
    chinese: "的",
    pinyin: "De",
  },
  { russian: "этот, эти", chinese: "这个", pinyin: "Zhege" },
  { russian: "Следующий", chinese: "下个", pinyin: "Xiage" },
  { russian: "Предыдущий", chinese: "上个", pinyin: "Shangge" },
  { russian: "Вместе", chinese: "一起", pinyin: "Yiqi" },
  { russian: "И, с", chinese: "和", pinyin: "He" },
  { russian: "С (кем-то)", chinese: "跟", pinyin: "Gen" },
  { russian: "Также, тоже", chinese: "还", pinyin: "Hai" },
  { russian: "Или (в вопросах)", chinese: "还是", pinyin: "Haishi" },
  { russian: "Или (в утвердительных)", chinese: "或者", pinyin: "Huozhe" },
  { russian: "Суффикс продолжающегося действия", chinese: "着", pinyin: "Zhe" },
  {
    russian: "Суффикс завершенного действия (present perfect)",
    chinese: "过",
    pinyin: "Guo",
  },
  {
    russian: "Добавляется к глаголам чтобы показать результат",
    chinese: "到",
    pinyin: "Dao",
  },
  {
    russian: "Соединительная частица глаголов и наречий",
    chinese: "得",
    pinyin: "De",
  },
  {
    russian:
      "Обозначает, что действие происходит в какой-то момент (present continuous)",
    chinese: "正在",
    pinyin: "Zhengzai",
  },
  { russian: "Дательный падеж", chinese: "给", pinyin: "Gei" },
  { russian: "Наверное", chinese: "可能", pinyin: "Keneng" },
  { russian: "Запрет /совет что-то не делать", chinese: "别", pinyin: "Bie" },
  { russian: "Если", chinese: "如果", pinyin: "Ruguo" },
  { russian: "То (после если)", chinese: "就", pinyin: "Jiu" },
  { russian: "Сначала", chinese: "先", pinyin: "Xian" },
  { russian: "Потом", chinese: "然后", pinyin: "Ranhou" },
  { russian: "Еще раз, потом", chinese: "再", pinyin: "Zai" },
  { russian: "Винительный падеж", chinese: "把", pinyin: "Ba" },
  { russian: "Итого", chinese: "一共", pinyin: "Yigong" },
  { russian: "Но", chinese: "可是", pinyin: "Keshi" },
  { russian: "Поэтому", chinese: "所以", pinyin: "Suoyi" },
  { russian: "Помимо", chinese: "除了", pinyin: "Chule" },
  { russian: "Образует пассивную форму", chinese: "被", pinyin: "Bei" },
  { russian: "Потому что", chinese: "因为", pinyin: "Yinwei" },
  { russian: "Вопросительная частица", chinese: "吗", pinyin: "Ma" },
  { russian: "Что", chinese: "什么", pinyin: "Shenme" },
  { russian: "Кто", chinese: "谁", pinyin: "Shei" },
  { russian: "А (ты)?", chinese: "呢", pinyin: "Ne" },
  { russian: "Где", chinese: "哪里", pinyin: "Nali" },
  {
    russian: "Сколько (про маленькое количество – до 5-9)",
    chinese: "几",
    pinyin: "Ji",
  },
  { russian: "Сколько", chinese: "多少", pinyin: "Duoshao" },
  { russian: "Сколько лет", chinese: "多大", pinyin: "Duoda" },
  { russian: "Как долго", chinese: "多久", pinyin: "Duojiu" },
  { russian: "Какой, какая, какое", chinese: "哪", pinyin: "Na" },
  { russian: "Что делаешь", chinese: "干什么", pinyin: "Ganshenme" },
  { russian: "Когда", chinese: "什么时候", pinyin: "Shenmeshihou" },
  { russian: "Как", chinese: "怎么", pinyin: "Zenme" },
  { russian: "Как (как тебе)", chinese: "怎么样", pinyin: "Zenmeyang" },
  { russian: "Частица формирующая предположения", chinese: "吧", pinyin: "Ba" },
  { russian: "Почему", chinese: "为什么", pinyin: "Weishenme" },
  { russian: "Хорошо?", chinese: "行吗", pinyin: "Xing ma" },
  { russian: "Китай", chinese: "中国", pinyin: "Zhongguo" },
  { russian: "Америка", chinese: "美国", pinyin: "Meiguo" },
  { russian: "Россия", chinese: "俄罗斯", pinyin: "Eluosi" },
  { russian: "Англия", chinese: "英国", pinyin: "Yingguo" },
  { russian: "Тайланд", chinese: "泰国", pinyin: "Taiguo" },
  { russian: "Франция", chinese: "法国", pinyin: "Faguo" },
  { russian: "Германия", chinese: "德国", pinyin: "Deguo" },
  { russian: "Шанхай", chinese: "上海", pinyin: "Shanghai" },
  { russian: "Пекин", chinese: "北京", pinyin: "Beijing" },
  { russian: "Гонконг", chinese: "香港", pinyin: "Xianggang" },
  { russian: "Китайский язык", chinese: "汉语", pinyin: "Hanyu" },
  { russian: "Английский язык", chinese: "英语", pinyin: "Yingyu" },
  { russian: "Привет", chinese: "你好", pinyin: "Nihao" },
  { russian: "Пока", chinese: "再见", pinyin: "Zaijian" },
  { russian: "Спасибо", chinese: "谢谢", pinyin: "Xiexie" },
  { russian: "Большое спасибо", chinese: "多谢", pinyin: "Duoxie" },
  {
    russian: "Пожалуйста (в ответ на спасибо)",
    chinese: "不客气",
    pinyin: "Bukeqi",
  },
  { russian: "Извините", chinese: "对不起", pinyin: "Duibuqi" },
  { russian: "Пожалуйста (при просьбе)", chinese: "请", pinyin: "Qing" },
  { russian: "Извините (при просьбе)", chinese: "请问", pinyin: "Qingwen" },
  { russian: "Не стоит переживать", chinese: "没关系", pinyin: "Meiguanxi" },
  { russian: "Алё", chinese: "喂", pinyin: "Wei" },
  { russian: "0", chinese: "零", pinyin: "Ling" },
  { russian: "1", chinese: "一", pinyin: "Yi" },
  { russian: "2", chinese: "两", pinyin: "Liang" },
  { russian: "2", chinese: "二", pinyin: "Er" },
  { russian: "3", chinese: "三", pinyin: "San" },
  { russian: "4", chinese: "四", pinyin: "Si" },
  { russian: "5", chinese: "五", pinyin: "Wu" },
  { russian: "6", chinese: "六", pinyin: "Liu" },
  { russian: "7", chinese: "七", pinyin: "Qi" },
  { russian: "8", chinese: "八", pinyin: "Ba" },
  { russian: "9", chinese: "九", pinyin: "Jiu" },
  { russian: "10", chinese: "十", pinyin: "Shi" },
  { russian: "100", chinese: "百", pinyin: "Bai" },
  { russian: "1000", chinese: "千", pinyin: "Qian" },
  { russian: "10000", chinese: "万", pinyin: "Wan" },
  { russian: "100000000", chinese: "亿", pinyin: "Yi" },
];

export { wordList };
