let wordList = [
  { russian: "я", chinese: "我", pinyin: "wǒ", category: "Местоимения" },
  { russian: "ты", chinese: "你", pinyin: "nǐ", category: "Местоимения" },
  { russian: "он", chinese: "他", pinyin: "tā", category: "Местоимения" },
  { russian: "она", chinese: "她", pinyin: "tā", category: "Местоимения" },
  { russian: "оно", chinese: "它", pinyin: "tā", category: "Местоимения" },
  {
    russian: "множ. число",
    chinese: "们",
    pinyin: "men",
    category: "Местоимения",
  },
  { russian: "мама", chinese: "妈妈", pinyin: "māma", category: "Семья" },
  { russian: "папа", chinese: "爸爸", pinyin: "bàba", category: "Семья" },
  { russian: "сын", chinese: "儿子", pinyin: "érzi", category: "Семья" },
  { russian: "дочь", chinese: "奴儿", pinyin: "nú'ér", category: "Семья" },
  {
    russian: "старший брат",
    chinese: "哥哥",
    pinyin: "gēge",
    category: "Семья",
  },
  {
    russian: "старшая сестра",
    chinese: "姐姐",
    pinyin: "jiějie",
    category: "Семья",
  },
  {
    russian: "младший брат",
    chinese: "弟弟",
    pinyin: "dìdi",
    category: "Семья",
  },
  {
    russian: "младшая сестра",
    chinese: "妹妹",
    pinyin: "mèimei",
    category: "Семья",
  },
  { russian: "дедушка", chinese: "爷爷", pinyin: "yéye", category: "Семья" },
  { russian: "бабушка", chinese: "奶奶", pinyin: "nǎinai", category: "Семья" },
  { russian: "семья", chinese: "家", pinyin: "jiā", category: "Семья" },
  { russian: "ребенок", chinese: "孩子", pinyin: "háizi", category: "Семья" },
  {
    russian: "парень",
    chinese: "男朋友",
    pinyin: "nán péngyǒu",
    category: "Семья",
  },
  {
    russian: "девушка",
    chinese: "奴朋友",
    pinyin: "nǔ péngyǒu",
    category: "Семья",
  },
  { russian: "друг", chinese: "朋友", pinyin: "péngyǒu", category: "Семья" },
  { russian: "Муж", chinese: "老公", pinyin: "Laogong", category: "Семья" },
  {
    russian: "Жена",
    chinese: "老婆",
    pinyin: "Laopo",
    category: "Семья",
  },
  { russian: "собака", chinese: "狗", pinyin: "gǒu", category: "Животные" },
  { russian: "кошка", chinese: "猫", pinyin: "māo", category: "Животные" },
  { russian: "овца", chinese: "羊", pinyin: "yáng", category: "Животные" },
  { russian: "корова", chinese: "牛", pinyin: "niú", category: "Животные" },
  { russian: "свинья", chinese: "猪", pinyin: "zhū", category: "Животные" },
  { russian: "рыба", chinese: "鱼", pinyin: "yú", category: "Животные" },
  { russian: "птица", chinese: "鸟", pinyin: "niǎo", category: "Животные" },
  { russian: "курица", chinese: "鸡", pinyin: "jī", category: "Животные" },
  {
    russian: "панда",
    chinese: "熊猫",
    pinyin: "xióngmāo",
    category: "Животные",
  },
  { russian: "кролик", chinese: "兔子", pinyin: "tùzi", category: "Животные" },
  {
    russian: "Напитки",
    chinese: "饮料",
    pinyin: "yǐnliào",
    category: "Напитки",
  },
  { russian: "Чай", chinese: "茶", pinyin: "chá", category: "Напитки" },
  { russian: "Вода", chinese: "水", pinyin: "shuǐ", category: "Напитки" },
  { russian: "Кофе", chinese: "咖啡", pinyin: "kāfēi", category: "Напитки" },
  { russian: "Кола", chinese: "可乐", pinyin: "kělè", category: "Напитки" },
  { russian: "Алкоголь", chinese: "酒", pinyin: "jiǔ", category: "Напитки" },
  { russian: "Пиво", chinese: "啤酒", pinyin: "píjiǔ", category: "Напитки" },
  { russian: "Водка", chinese: "白酒", pinyin: "báijiǔ", category: "Напитки" },
  { russian: "Сок", chinese: "果汁", pinyin: "guǒzhī", category: "Напитки" },
  { russian: "Молоко", chinese: "牛奶", pinyin: "niúnǎi", category: "Напитки" },
  {
    russian: "Минеральная вода",
    chinese: "矿泉水",
    pinyin: "kuàngquán shuǐ",
    category: "Напитки",
  },
  { russian: "Свинина", chinese: "猪肉", pinyin: "zhūròu", category: "Еда" },
  { russian: "Говядина", chinese: "牛肉", pinyin: "niúròu", category: "Еда" },
  { russian: "Яйца", chinese: "鸡蛋", pinyin: "jīdàn", category: "Еда" },
  { russian: "Хлеб", chinese: "面包", pinyin: "miànbāo", category: "Еда" },
  { russian: "Овощи", chinese: "蔬菜", pinyin: "shūcài", category: "Еда" },
  { russian: "Фрукты", chinese: "水果", pinyin: "shuǐguǒ", category: "Еда" },
  { russian: "Торт", chinese: "蛋糕", pinyin: "dàngāo", category: "Еда" },
  { russian: "Печенье", chinese: "饼干", pinyin: "bǐnggān", category: "Еда" },
  { russian: "Яблоко", chinese: "苹果", pinyin: "píngguǒ", category: "Еда" },
  { russian: "Манго", chinese: "芒果", pinyin: "mángguǒ", category: "Еда" },
  { russian: "Ананас", chinese: "菠萝", pinyin: "bōluó", category: "Еда" },
  { russian: "Арбуз", chinese: "西瓜", pinyin: "xīguā", category: "Еда" },
  { russian: "Рис", chinese: "米饭", pinyin: "mǐfàn", category: "Еда" },
  { russian: "Суп", chinese: "汤", pinyin: "tāng", category: "Еда" },
  { russian: "Пельмени", chinese: "饺子", pinyin: "jiǎozi", category: "Еда" },
  { russian: "Лапша", chinese: "面条", pinyin: "miàntiáo", category: "Еда" },
  { russian: "Стейк", chinese: "牛排", pinyin: "niúpái", category: "Еда" },
  { russian: "Салат", chinese: "沙拉", pinyin: "shālā", category: "Еда" },
  { russian: "Лимон", chinese: "柠檬", pinyin: "níngméng", category: "Еда" },
  { russian: "Гамбургер", chinese: "汉堡", pinyin: "hànbǎo", category: "Еда" },
  {
    russian: "Картофель фри",
    chinese: "薯条",
    pinyin: "shǔtiáo",
    category: "Еда",
  },
  { russian: "Огурец", chinese: "黄瓜", pinyin: "huángguā", category: "Еда" },
  {
    russian: "Помидоры",
    chinese: "西红柿",
    pinyin: "xīhóngshì",
    category: "Еда",
  },
  { russian: "Сельдерей", chinese: "芹菜", pinyin: "qíncài", category: "Еда" },
  { russian: "Морковь", chinese: "胡萝卜", pinyin: "húluóbo", category: "Еда" },
  { russian: "Банан", chinese: "香蕉", pinyin: "xiāngjiāo", category: "Еда" },
  { russian: "Апельсин", chinese: "橙子", pinyin: "chéngzi", category: "Еда" },
  { russian: "Клубника", chinese: "草莓", pinyin: "cǎoméi", category: "Еда" },
  {
    russian: "Шоколад",
    chinese: "巧克力",
    pinyin: "qiǎokèlì",
    category: "Еда",
  },
  { russian: "Мандарины", chinese: "橘子", pinyin: "júzi", category: "Еда" },
  {
    russian: "Жареная утка",
    chinese: "烤鸭",
    pinyin: "kǎoyā",
    category: "Еда",
  },
  {
    russian: "Основное блюдо",
    chinese: "主食",
    pinyin: "zhǔshí",
    category: "Еда",
  },
  { russian: "Закуски", chinese: "小吃", pinyin: "xiǎochī", category: "Еда" },
  { russian: "Сыр", chinese: "芝士", pinyin: "zhīshì", category: "Еда" },
  { russian: "Виноград", chinese: "葡萄", pinyin: "pútáo", category: "Еда" },
  { russian: "Грибы", chinese: "蘑菇", pinyin: "mógu", category: "Еда" },
  {
    russian: "Листовой салат",
    chinese: "生菜",
    pinyin: "shēngcài",
    category: "Еда",
  },
  { russian: "Быть", chinese: "是", pinyin: "shì", category: "Глаголы" },
  { russian: "Иметь", chinese: "有", pinyin: "yǒu", category: "Глаголы" },
  { russian: "Любить", chinese: "爱", pinyin: "ài", category: "Глаголы" },
  {
    russian: "Нравиться",
    chinese: "喜欢",
    pinyin: "xǐhuān",
    category: "Глаголы",
  },
  { russian: "Есть", chinese: "吃", pinyin: "chī", category: "Глаголы" },
  {
    russian: "Есть еду",
    chinese: "吃饭",
    pinyin: "chīfàn",
    category: "Глаголы",
  },
  { russian: "Пить", chinese: "喝", pinyin: "hē", category: "Глаголы" },
  {
    russian: "Звать, называть",
    chinese: "叫",
    pinyin: "jiào",
    category: "Глаголы",
  },
  { russian: "Говорить", chinese: "说", pinyin: "shuō", category: "Глаголы" },
  {
    russian: "Разговаривать",
    chinese: "说话",
    pinyin: "shuōhuà",
    category: "Глаголы",
  },
  {
    russian: "Разговаривать (неформ.)",
    chinese: "聊天",
    pinyin: "liáotiān",
    category: "Глаголы",
  },
  { russian: "Учить", chinese: "学", pinyin: "xué", category: "Глаголы" },
  { russian: "Изучать", chinese: "学习", pinyin: "xuéxí", category: "Глаголы" },
  { russian: "Покупать", chinese: "买", pinyin: "mǎi", category: "Глаголы" },
  { russian: "Продавать", chinese: "卖", pinyin: "mài", category: "Глаголы" },
  { russian: "Хотеть", chinese: "想", pinyin: "xiǎng", category: "Глаголы" },
  {
    russian: "Хотеть, нуждаться",
    chinese: "要",
    pinyin: "yào",
    category: "Глаголы",
  },
  { russian: "Давать", chinese: "给", pinyin: "gěi", category: "Глаголы" },
  { russian: "Идти", chinese: "去", pinyin: "qù", category: "Глаголы" },
  { russian: "Находиться", chinese: "在", pinyin: "zài", category: "Глаголы" },
  { russian: "Мыть", chinese: "洗", pinyin: "xǐ", category: "Глаголы" },
  {
    russian: "Принимать душ, купаться",
    chinese: "洗澡",
    pinyin: "xǐzǎo",
    category: "Глаголы",
  },
  {
    russian: "Умываться",
    chinese: "洗脸",
    pinyin: "xǐliǎn",
    category: "Глаголы",
  },
  {
    russian: "Вставать с постели",
    chinese: "起床",
    pinyin: "qǐchuáng",
    category: "Глаголы",
  },
  {
    russian: "Начинать работу",
    chinese: "上班",
    pinyin: "shàngbān",
    category: "Глаголы",
  },
  {
    russian: "Заканчивать работу",
    chinese: "下班",
    pinyin: "xiàbān",
    category: "Глаголы",
  },
  {
    russian: "Чистить зубы",
    chinese: "刷牙",
    pinyin: "shuāyá",
    category: "Глаголы",
  },
  {
    russian: "Начинать учебу, занятие",
    chinese: "上课",
    pinyin: "shàngkè",
    category: "Глаголы",
  },
  {
    russian: "Заказчивать учебу, занятие",
    chinese: "下课",
    pinyin: "xiàkè",
    category: "Глаголы",
  },
  {
    russian: "Смотреть/читать",
    chinese: "看",
    pinyin: "kàn",
    category: "Глаголы",
  },
  {
    russian: "Видеть",
    chinese: "看见",
    pinyin: "kànjiàn",
    category: "Глаголы",
  },
  {
    russian: "Делать/готовить",
    chinese: "做",
    pinyin: "zuò",
    category: "Глаголы",
  },
  {
    russian: "Готовить еду",
    chinese: "做饭",
    pinyin: "zuòfàn",
    category: "Глаголы",
  },
  {
    russian: "Возвращаться",
    chinese: "回",
    pinyin: "huí",
    category: "Глаголы",
  },
  {
    russian: "Приходить (куда-то)",
    chinese: "来",
    pinyin: "lái",
    category: "Глаголы",
  },
  {
    russian: "Прибывать (куда-то)",
    chinese: "到",
    pinyin: "dào",
    category: "Глаголы",
  },
  {
    russian: "Мочь, иметь возможность",
    chinese: "能",
    pinyin: "néng",
    category: "Глаголы",
  },
  {
    russian: "Мочь, иметь возможность",
    chinese: "可以",
    pinyin: "kěyǐ",
    category: "Глаголы",
  },
  {
    russian: "Спать",
    chinese: "睡觉",
    pinyin: "shuìjiào",
    category: "Глаголы",
  },
  { russian: "Петь", chinese: "唱", pinyin: "chàng", category: "Глаголы" },
  {
    russian: "Танцевать",
    chinese: "跳舞",
    pinyin: "tiàowǔ",
    category: "Глаголы",
  },
  {
    russian: "Рисовать",
    chinese: "画画",
    pinyin: "huàhuà",
    category: "Глаголы",
  },
  {
    russian: "Кататься на лыжах",
    chinese: "滑雪",
    pinyin: "huáxuě",
    category: "Глаголы",
  },
  {
    russian: "Путешествовать",
    chinese: "旅游",
    pinyin: "lǚyóu",
    category: "Глаголы",
  },
  {
    russian: "Открывать, включать",
    chinese: "开",
    pinyin: "kāi",
    category: "Глаголы",
  },
  {
    russian: "Закрывать, выключать",
    chinese: "关",
    pinyin: "guān",
    category: "Глаголы",
  },
  { russian: "Помогать", chinese: "帮", pinyin: "bāng", category: "Глаголы" },
  { russian: "Ждать", chinese: "等", pinyin: "děng", category: "Глаголы" },
  { russian: "Искать", chinese: "找", pinyin: "zhǎo", category: "Глаголы" },
  {
    russian: "Сталкиваться (с кем-то)",
    chinese: "遇到",
    pinyin: "yùdào",
    category: "Глаголы",
  },
  {
    russian: "Заканчиваться",
    chinese: "结束",
    pinyin: "jiéshù",
    category: "Глаголы",
  },
  {
    russian: "Опаздывать",
    chinese: "迟到",
    pinyin: "chídào",
    category: "Глаголы",
  },
  {
    russian: "Начинаться",
    chinese: "开始",
    pinyin: "kāishǐ",
    category: "Глаголы",
  },
  {
    russian: "Убираться, чистить",
    chinese: "打扫",
    pinyin: "dǎsǎo",
    category: "Глаголы",
  },
  { russian: "Слушать", chinese: "听", pinyin: "tīng", category: "Глаголы" },
  {
    russian: "Слушаться",
    chinese: "听话",
    pinyin: "tīnghuà",
    category: "Глаголы",
  },
  { russian: "Играть", chinese: "玩", pinyin: "wán", category: "Глаголы" },
  {
    russian: "Сделать и получить результат (доделать)",
    chinese: "完",
    pinyin: "wán",
    category: "Глаголы",
  },
  {
    russian: "Серфить в интернете",
    chinese: "上网",
    pinyin: "shàngwǎng",
    category: "Глаголы",
  },
  {
    russian: "Надевать, носить (пальто, рубашку …)",
    chinese: "穿",
    pinyin: "chuān",
    category: "Глаголы",
  },
  {
    russian: "Надевать, носить (шапку, очки, перчатки)",
    chinese: "戴",
    pinyin: "dài",
    category: "Глаголы",
  },
  {
    russian: "Думать, полагать",
    chinese: "觉得",
    pinyin: "juédé",
    category: "Глаголы",
  },
  {
    russian: "Примерять (одежду)",
    chinese: "试",
    pinyin: "shì",
    category: "Глаголы",
  },
  {
    russian: "Попробовать (еду)",
    chinese: "尝",
    pinyin: "cháng",
    category: "Глаголы",
  },
  {
    russian: "Забронировать",
    chinese: "预订",
    pinyin: "yùdìng",
    category: "Глаголы",
  },
  {
    russian: "Использовать",
    chinese: "用",
    pinyin: "yòng",
    category: "Глаголы",
  },
  { russian: "Звонить", chinese: "打", pinyin: "dǎ", category: "Глаголы" },
  {
    russian: "Играть (в спорт руками)",
    chinese: "打",
    pinyin: "dǎ",
    category: "Глаголы",
  },
  {
    russian: "Уметь (иметь приобретенный навык)",
    chinese: "会",
    pinyin: "huì",
    category: "Глаголы",
  },
  { russian: "Пинать (мяч)", chinese: "踢", pinyin: "tī", category: "Глаголы" },
  { russian: "Кататься", chinese: "骑", pinyin: "qí", category: "Глаголы" },
  { russian: "Бегать", chinese: "跑步", pinyin: "pǎobù", category: "Глаголы" },
  { russian: "Гулять", chinese: "散步", pinyin: "sànbù", category: "Глаголы" },
  {
    russian: "Идти пешком",
    chinese: "走路",
    pinyin: "zǒulù",
    category: "Глаголы",
  },
  {
    russian: "Прогуливаться",
    chinese: "逛",
    pinyin: "guàng",
    category: "Глаголы",
  },
  {
    russian: "Плавать",
    chinese: "游泳",
    pinyin: "yóuyǒng",
    category: "Глаголы",
  },
  {
    russian: "Следует (должно, нужно)",
    chinese: "应该",
    pinyin: "yīnggāi",
    category: "Глаголы",
  },
  {
    russian: "Требуется",
    chinese: "需要",
    pinyin: "xūyào",
    category: "Глаголы",
  },
  {
    russian: "Не спать всю ночь",
    chinese: "熬夜",
    pinyin: "áoyè",
    category: "Глаголы",
  },
  {
    russian: "Ругаться",
    chinese: "吵架",
    pinyin: "chǎojià",
    category: "Глаголы",
  },
  {
    russian: "Расставаться",
    chinese: "分手",
    pinyin: "fēnshǒu",
    category: "Глаголы",
  },
  {
    russian: "Жениться",
    chinese: "结婚",
    pinyin: "jiéhūn",
    category: "Глаголы",
  },
  {
    russian: "Встретиться",
    chinese: "见面",
    pinyin: "jiànmiàn",
    category: "Глаголы",
  },
  {
    russian: "Пригласить, позаботиться",
    chinese: "请",
    pinyin: "qǐng",
    category: "Глаголы",
  },
  {
    russian: "Проводить, довезти",
    chinese: "送",
    pinyin: "sòng",
    category: "Глаголы",
  },
  { russian: "Дарить", chinese: "送", pinyin: "sòng", category: "Глаголы" },
  {
    russian: "Работать",
    chinese: "工作",
    pinyin: "gōngzuò",
    category: "Глаголы",
  },
  {
    russian: "Стать (кем-то)",
    chinese: "当",
    pinyin: "dāng",
    category: "Глаголы",
  },
  { russian: "Приносить", chinese: "拿", pinyin: "ná", category: "Глаголы" },
  {
    russian: "Совещаться",
    chinese: "开会",
    pinyin: "kāihuì",
    category: "Глаголы",
  },
  {
    russian: "Быть в командировке",
    chinese: "出差",
    pinyin: "chūchāi",
    category: "Глаголы",
  },
  {
    russian: "Распечатывать, печатать",
    chinese: "打印",
    pinyin: "dǎyìn",
    category: "Глаголы",
  },
  {
    russian: "Копировать, ксерокопировать",
    chinese: "复印",
    pinyin: "fùyìn",
    category: "Глаголы",
  },
  {
    russian: "Сидеть (ехать в транспорте)",
    chinese: "坐",
    pinyin: "zuò",
    category: "Глаголы",
  },
  {
    russian: "Вести машину",
    chinese: "开车",
    pinyin: "kāichē",
    category: "Глаголы",
  },
  { russian: "Отправлять", chinese: "发", pinyin: "fā", category: "Глаголы" },
  {
    russian: "Отвечать на звонок",
    chinese: "接",
    pinyin: "jiē",
    category: "Глаголы",
  },
  {
    russian: "Получать (сообщение)",
    chinese: "收",
    pinyin: "shōu",
    category: "Глаголы",
  },
  {
    russian: "Испытывать боль",
    chinese: "疼",
    pinyin: "téng",
    category: "Глаголы",
  },
  {
    russian: "Простужаться",
    chinese: "感冒",
    pinyin: "gǎnmào",
    category: "Глаголы",
  },
  {
    russian: "Температурить",
    chinese: "发烧",
    pinyin: "fāshāo",
    category: "Глаголы",
  },
  { russian: "Болеть", chinese: "病", pinyin: "bìng", category: "Глаголы" },
  {
    russian: "Болеть",
    chinese: "生病",
    pinyin: "shēngbìng",
    category: "Глаголы",
  },
  {
    russian: "Отдыхать",
    chinese: "休息",
    pinyin: "xiūxí",
    category: "Глаголы",
  },
  { russian: "Класть", chinese: "放", pinyin: "fàng", category: "Глаголы" },
  {
    russian: "Сделать что-то",
    chinese: "弄",
    pinyin: "nòng",
    category: "Глаголы",
  },
  { russian: "Портить", chinese: "坏", pinyin: "huài", category: "Глаголы" },
  { russian: "Терять", chinese: "丢", pinyin: "diū", category: "Глаголы" },
  {
    russian: "Знать (что-то)",
    chinese: "知道",
    pinyin: "zhīdào",
    category: "Глаголы",
  },
  {
    russian: "Знать (кого-то)",
    chinese: "认识",
    pinyin: "rènshì",
    category: "Глаголы",
  },
  { russian: "Ругать", chinese: "骂", pinyin: "mà", category: "Глаголы" },
  { russian: "Красть", chinese: "偷", pinyin: "tōu", category: "Глаголы" },
  { russian: "Врать", chinese: "骗", pinyin: "piàn", category: "Глаголы" },
  {
    russian: "Растить, иметь животное",
    chinese: "养",
    pinyin: "yǎng",
    category: "Глаголы",
  },
  {
    russian: "Решиться, дерзнуть",
    chinese: "敢",
    pinyin: "gǎn",
    category: "Глаголы",
  },
  { russian: "Писать", chinese: "写", pinyin: "xie", category: "Глаголы" },
  {
    russian: "Гладить (животное)",
    chinese: "摸",
    pinyin: "mō",
    category: "Глаголы",
  },
  {
    russian: "Выходить из дома",
    chinese: "出门",
    pinyin: "chūmén",
    category: "Глаголы",
  },
  {
    russian: "Составлять компанию",
    chinese: "陪",
    pinyin: "péi",
    category: "Глаголы",
  },
  { russian: "Кашлять", chinese: "咳嗽", pinyin: "késòu", category: "Глаголы" },
  {
    russian: "Давать разрешение, велеть",
    chinese: "让",
    pinyin: "ràng",
    category: "Глаголы",
  },
  {
    russian: "Делать укол",
    chinese: "打针",
    pinyin: "dǎzhēn",
    category: "Глаголы",
  },
  {
    russian: "Госпитализировать",
    chinese: "住院",
    pinyin: "zhùyuàn",
    category: "Глаголы",
  },
  {
    russian: "Заказывать (в ресторане)",
    chinese: "点菜",
    pinyin: "diǎncài",
    category: "Глаголы",
  },
  {
    russian: "Оплачивать счет (в ресторане)",
    chinese: "买单",
    pinyin: "mǎidān",
    category: "Глаголы",
  },
  {
    russian: "Забрать остатки",
    chinese: "打包",
    pinyin: "dǎbāo",
    category: "Глаголы",
  },
  { russian: "Повернуть", chinese: "拐", pinyin: "guǎi", category: "Глаголы" },
  {
    russian: "Тренироваться (заниматься фитнесом)",
    chinese: "健身",
    pinyin: "jiànshēn",
    category: "Глаголы",
  },

  { russian: "Писать", chinese: "写", pinyin: "xiě", category: "Глаголы" },
  {
    russian: "Фотографировать",
    chinese: "拍",
    pinyin: "pāi",
    category: "Глаголы",
  },
  {
    russian: "Переносить, передвигать (тяжелые объекты)",
    chinese: "搬",
    pinyin: "bān",
    category: "Глаголы",
  },
  {
    russian: "Менять, меняться",
    chinese: "换",
    pinyin: "huàn",
    category: "Глаголы",
  },
  { russian: "Выбирать", chinese: "挑", pinyin: "tiāo", category: "Глаголы" },
  {
    russian: "Решать, принять решение",
    chinese: "决定",
    pinyin: "juédìng",
    category: "Глаголы",
  },
  {
    russian: "Понимать",
    chinese: "了解",
    pinyin: "liǎojiě",
    category: "Глаголы",
  },
  {
    russian: "Учиться заграницей",
    chinese: "留学",
    pinyin: "liúxué",
    category: "Глаголы",
  },
  {
    russian: "Думать, полагать",
    chinese: "认为",
    pinyin: "rènwéi",
    category: "Глаголы",
  },
  { russian: "Читать", chinese: "读", pinyin: "dú", category: "Глаголы" },
  {
    russian: "Посещать (школу)",
    chinese: "上",
    pinyin: "shàng",
    category: "Глаголы",
  },
  {
    russian: "Должно, следует (время сделать …)",
    chinese: "该。。。了",
    pinyin: "gāi... le",
    category: "Глаголы",
  },
  {
    russian: "Сдавать экзамен",
    chinese: "考试",
    pinyin: "kǎoshì",
    category: "Глаголы",
  },
  {
    russian: "Выпуститься (из учебного заведения)",
    chinese: "毕业",
    pinyin: "bìyè",
    category: "Глаголы",
  },
  {
    russian: "Подготовиться (к экзамену)",
    chinese: "复习",
    pinyin: "fùxí",
    category: "Глаголы",
  },
  {
    russian: "Соглашаться",
    chinese: "同意",
    pinyin: "tóngyì",
    category: "Глаголы",
  },
  {
    russian: "Хотеть сделать что-то",
    chinese: "愿意",
    pinyin: "yuànyì",
    category: "Глаголы",
  },
  {
    russian: "Извиниться",
    chinese: "道歉",
    pinyin: "dàoqiàn",
    category: "Глаголы",
  },
  {
    russian: "Развестись",
    chinese: "离婚",
    pinyin: "líhūn",
    category: "Глаголы",
  },
  {
    russian: "Встречаться (иметь отношения)",
    chinese: "谈恋爱",
    pinyin: "tán liàn'ài",
    category: "Глаголы",
  },
  {
    russian: "Улыбаться, смеяться",
    chinese: "笑",
    pinyin: "xiào",
    category: "Глаголы",
  },
  { russian: "Плакать", chinese: "哭", pinyin: "kū", category: "Глаголы" },
  {
    russian: "Штука (общее сч.слово)",
    chinese: "个",
    pinyin: "gè",
    category: "Счетные слова",
  },
  {
    russian: "Раз (к действиям)",
    chinese: "次",
    pinyin: "cì",
    category: "Счетные слова",
  },
  {
    russian: "Раз (к перемещениям)",
    chinese: "趟",
    pinyin: "tàng",
    category: "Счетные слова",
  },
  {
    russian: "Раз (к завершенным действиям)",
    chinese: "遍",
    pinyin: "biàn",
    category: "Счетные слова",
  },
  { russian: "Вид", chinese: "种", pinyin: "zhǒng", category: "Счетные слова" },
  {
    russian: "К порядковым числительным",
    chinese: "第",
    pinyin: "dì",
    category: "Счетные слова",
  },
  {
    russian: "Слайс (кусочек хлеба, и т.д.)",
    chinese: "片",
    pinyin: "piàn",
    category: "Счетные слова",
  },
  {
    russian: "Денежная единица",
    chinese: "块",
    pinyin: "kuài",
    category: "Счетные слова",
  },
  {
    russian: "К длинным тонким предметам",
    chinese: "支",
    pinyin: "zhī",
    category: "Счетные слова",
  },
  {
    russian: "К плоским предметам",
    chinese: "张",
    pinyin: "zhāng",
    category: "Счетные слова",
  },
  {
    russian: "К технике",
    chinese: "部",
    pinyin: "bù",
    category: "Счетные слова",
  },
  {
    russian: "К технике",
    chinese: "台",
    pinyin: "tái",
    category: "Счетные слова",
  },
  {
    russian: "Пакет (молока и т.п.)",
    chinese: "袋",
    pinyin: "dài",
    category: "Счетные слова",
  },
  {
    russian: "Коробка (молока и т.п.)",
    chinese: "盒",
    pinyin: "hé",
    category: "Счетные слова",
  },
  {
    russian: "К животным (кошка, собака)",
    chinese: "只",
    pinyin: "zhī",
    category: "Счетные слова",
  },
  { russian: "Годик", chinese: "岁", pinyin: "suì", category: "Счетные слова" },
  {
    russian: "Стакан",
    chinese: "杯",
    pinyin: "bēi",
    category: "Счетные слова",
  },
  {
    russian: "Плошка",
    chinese: "碗",
    pinyin: "wǎn",
    category: "Счетные слова",
  },
  {
    russian: "Тарелка",
    chinese: "盘",
    pinyin: "pán",
    category: "Счетные слова",
  },
  {
    russian: "Кусок (торта)",
    chinese: "块",
    pinyin: "kuài",
    category: "Счетные слова",
  },
  {
    russian: "Бутылка",
    chinese: "瓶",
    pinyin: "píng",
    category: "Счетные слова",
  },
  {
    russian: "К членам семьи",
    chinese: "口",
    pinyin: "kǒu",
    category: "Счетные слова",
  },
  {
    russian: "Пара",
    chinese: "双",
    pinyin: "shuāng",
    category: "Счетные слова",
  },
  { russian: "Блюдо", chinese: "菜", pinyin: "cài", category: "Счетные слова" },
  {
    russian: "К документам",
    chinese: "份",
    pinyin: "fèn",
    category: "Счетные слова",
  },
  {
    russian: "К вещам (пальто, рубашка)",
    chinese: "件",
    pinyin: "jiàn",
    category: "Счетные слова",
  },
  {
    russian: "К длинным предметам (штаны, дороги, реки)",
    chinese: "条",
    pinyin: "tiáo",
    category: "Счетные слова",
  },
  {
    russian: "Килограмм",
    chinese: "公斤",
    pinyin: "gōngjīn",
    category: "Счетные слова",
  },
  {
    russian: "Полкило",
    chinese: "斤",
    pinyin: "jīn",
    category: "Счетные слова",
  },
  {
    russian: "К книгам",
    chinese: "本",
    pinyin: "běn",
    category: "Счетные слова",
  },
  {
    russian: "К цветам и облакам",
    chinese: "朵",
    pinyin: "duǒ",
    category: "Счетные слова",
  },
  {
    russian: "Несколько",
    chinese: "些",
    pinyin: "xiē",
    category: "Счетные слова",
  },
  { russian: "Чашка", chinese: "杯子", pinyin: "bēizi", category: "Посуда" },
  { russian: "Вилка", chinese: "叉子", pinyin: "chāzi", category: "Посуда" },
  { russian: "Ложка", chinese: "勺子", pinyin: "sháozi", category: "Посуда" },
  { russian: "Палочки", chinese: "筷子", pinyin: "kuàizi", category: "Посуда" },
  { russian: "Время", chinese: "时间", pinyin: "shíjiān", category: "Время" },
  {
    russian: "Час (который час)",
    chinese: "点",
    pinyin: "diǎn",
    category: "Время",
  },
  {
    russian: "Минута (который час)",
    chinese: "分",
    pinyin: "fēn",
    category: "Время",
  },
  {
    russian: "Час (астрономический)",
    chinese: "小时",
    pinyin: "xiǎoshí",
    category: "Время",
  },
  {
    russian: "Минута (астрономическая)",
    chinese: "分钟",
    pinyin: "fēnzhōng",
    category: "Время",
  },
  {
    russian: "Раннее утро",
    chinese: "早上",
    pinyin: "zǎoshàng",
    category: "Время",
  },
  {
    russian: "Первая половина дня",
    chinese: "上午",
    pinyin: "shàngwǔ",
    category: "Время",
  },
  { russian: "Полдень", chinese: "中午", pinyin: "zhōngwǔ", category: "Время" },
  {
    russian: "Вторая половина дня",
    chinese: "下午",
    pinyin: "xiàwǔ",
    category: "Время",
  },
  {
    russian: "Вечер, ночь",
    chinese: "晚上",
    pinyin: "wǎnshàng",
    category: "Время",
  },
  { russian: "Сейчас", chinese: "现在", pinyin: "xiànzài", category: "Время" },
  {
    russian: "До, перед (по времени)",
    chinese: "以前",
    pinyin: "yǐqián",
    category: "Время",
  },
  {
    russian: "После (по времени)",
    chinese: "以后",
    pinyin: "yǐhòu",
    category: "Время",
  },
  { russian: "Завтрак", chinese: "早饭", pinyin: "zǎofàn", category: "Время" },
  { russian: "Обед", chinese: "午饭", pinyin: "wǔfàn", category: "Время" },
  { russian: "Ужин", chinese: "晚饭", pinyin: "wǎnfàn", category: "Время" },
  {
    russian: "Неделя",
    chinese: "星期",
    pinyin: "xīngqī",
    category: "Дни, даты",
  },
  {
    russian: "Понедельник",
    chinese: "星期一",
    pinyin: "xīngqīyī",
    category: "Дни, даты",
  },
  {
    russian: "Вторник",
    chinese: "星期二",
    pinyin: "xīngqī'èr",
    category: "Дни, даты",
  },
  {
    russian: "Среда",
    chinese: "星期三",
    pinyin: "xīngqīsān",
    category: "Дни, даты",
  },
  {
    russian: "Четверг",
    chinese: "星期四",
    pinyin: "xīngqīsì",
    category: "Дни, даты",
  },
  {
    russian: "Пятница",
    chinese: "星期五",
    pinyin: "xīngqīwǔ",
    category: "Дни, даты",
  },
  {
    russian: "Суббота",
    chinese: "星期六",
    pinyin: "xīngqīliù",
    category: "Дни, даты",
  },
  {
    russian: "Воскресенье",
    chinese: "星期天",
    pinyin: "xīngqītiān",
    category: "Дни, даты",
  },
  {
    russian: "Сегодня",
    chinese: "今天",
    pinyin: "jīntiān",
    category: "Дни, даты",
  },
  {
    russian: "Завтра",
    chinese: "明天",
    pinyin: "míngtiān",
    category: "Дни, даты",
  },
  {
    russian: "Вчера",
    chinese: "昨天",
    pinyin: "zuótiān",
    category: "Дни, даты",
  },
  { russian: "Год", chinese: "年", pinyin: "nián", category: "Дни, даты" },
  { russian: "Месяц", chinese: "月", pinyin: "yuè", category: "Дни, даты" },
  {
    russian: "День (месяца)",
    chinese: "号",
    pinyin: "hào",
    category: "Дни, даты",
  },
  {
    russian: "День рождения",
    chinese: "生日",
    pinyin: "shēngrì",
    category: "Дни, даты",
  },
  {
    russian: "Каждый день",
    chinese: "每天",
    pinyin: "měitiān",
    category: "Дни, даты",
  },
  {
    russian: "Выходные",
    chinese: "周末",
    pinyin: "zhōumò",
    category: "Дни, даты",
  },
  {
    russian: "Ресторан",
    chinese: "饭馆",
    pinyin: "fànguǎn",
    category: "Места",
  },
  { russian: "Парк", chinese: "公园", pinyin: "gōngyuán", category: "Места" },
  {
    russian: "Школа, учебное заведение",
    chinese: "学校",
    pinyin: "xuéxiào",
    category: "Места",
  },
  { russian: "Банк", chinese: "银行", pinyin: "yínháng", category: "Места" },
  {
    russian: "Супермаркет",
    chinese: "超市",
    pinyin: "chāoshì",
    category: "Места",
  },
  {
    russian: "Магазин",
    chinese: "商店",
    pinyin: "shāngdiàn",
    category: "Места",
  },
  {
    russian: "Аэропорт",
    chinese: "机场",
    pinyin: "jīchǎng",
    category: "Места",
  },
  { russian: "Больница", chinese: "医院", pinyin: "yīyuàn", category: "Места" },
  {
    russian: "Офис",
    chinese: "办公室",
    pinyin: "bàngōngshì",
    category: "Места",
  },
  { russian: "Компания", chinese: "公司", pinyin: "gōngsī", category: "Места" },
  { russian: "Отель", chinese: "酒店", pinyin: "jiǔdiàn", category: "Места" },
  {
    russian: "Пекарня",
    chinese: "面包店",
    pinyin: "miànbāodiàn",
    category: "Места",
  },
  {
    russian: "Кафе",
    chinese: "咖啡馆",
    pinyin: "kāfēiguǎn",
    category: "Места",
  },
  {
    russian: "Автозаправка",
    chinese: "加油站",
    pinyin: "jiāyóuzhàn",
    category: "Места",
  },
  {
    russian: "Зоопарк",
    chinese: "动物园",
    pinyin: "dòngwùyuán",
    category: "Места",
  },
  {
    russian: "Парковка",
    chinese: "停车场",
    pinyin: "tíngchēchǎng",
    category: "Места",
  },
  {
    russian: "Великая Китайская Стена",
    chinese: "长城",
    pinyin: "chángchéng",
    category: "Места",
  },
  {
    russian: "Учебный корпус",
    chinese: "教学楼",
    pinyin: "jiàoxuélóu",
    category: "Места",
  },
  { russian: "Общага", chinese: "宿舍", pinyin: "sùshè", category: "Места" },
  {
    russian: "Спортивная площадка",
    chinese: "运动场",
    pinyin: "yùndòngchǎng",
    category: "Места",
  },
  {
    russian: "Спортзал",
    chinese: "体育馆",
    pinyin: "tǐyùguǎn",
    category: "Места",
  },
  {
    russian: "Библиотека",
    chinese: "图书馆",
    pinyin: "túshūguǎn",
    category: "Места",
  },
  {
    russian: "Книжный магазин",
    chinese: "书店",
    pinyin: "shūdiàn",
    category: "Места",
  },
  {
    russian: "Тренажерный зал",
    chinese: "健身房",
    pinyin: "jiànshēnfáng",
    category: "Места",
  },
  { russian: "Туалет", chinese: "厕所", pinyin: "cèsuǒ", category: "Места" },
  { russian: "Почта", chinese: "邮局", pinyin: "yóujú", category: "Места" },
  { russian: "Лето", chinese: "夏天", pinyin: "xiàtiān", category: "Погода" },
  { russian: "Осень", chinese: "秋天", pinyin: "qiūtiān", category: "Погода" },
  { russian: "Весна", chinese: "春天", pinyin: "chūntiān", category: "Погода" },
  { russian: "Зима", chinese: "冬天", pinyin: "dōngtiān", category: "Погода" },
  {
    russian: "Ветренно",
    chinese: "刮风",
    pinyin: "guāfēng",
    category: "Погода",
  },
  {
    russian: "Идет снег",
    chinese: "下雪",
    pinyin: "xiàxuě",
    category: "Погода",
  },
  {
    russian: "Идет дождь",
    chinese: "下雨",
    pinyin: "xiàyǔ",
    category: "Погода",
  },
  {
    russian: "Солнечно",
    chinese: "晴天",
    pinyin: "qíngtiān",
    category: "Погода",
  },
  {
    russian: "Пасмурно",
    chinese: "阴天",
    pinyin: "yīntiān",
    category: "Погода",
  },
  { russian: "Погода", chinese: "天气", pinyin: "tiānqì", category: "Погода" },
  {
    russian: "Прохладно",
    chinese: "凉快",
    pinyin: "liángkuài",
    category: "Погода",
  },
  { russian: "Тепло", chinese: "暖和", pinyin: "nuǎnhuo", category: "Погода" },

  {
    russian: "Градусы",
    chinese: "度",
    pinyin: "dù",
    category: "Погода",
  },
  {
    russian: "Спереди",
    chinese: "前边",
    pinyin: "qiánbiān",
    category: "Навигация",
  },
  {
    russian: "Сзади",
    chinese: "后边",
    pinyin: "hòubiān",
    category: "Навигация",
  },
  { russian: "Рядом", chinese: "附近", pinyin: "fùjìn", category: "Навигация" },
  {
    russian: "На, над",
    chinese: "上边",
    pinyin: "shàngbiān",
    category: "Навигация",
  },
  { russian: "Под", chinese: "下边", pinyin: "xiàbiān", category: "Навигация" },
  {
    russian: "Север",
    chinese: "北边",
    pinyin: "běibiān",
    category: "Навигация",
  },
  { russian: "Юг", chinese: "南边", pinyin: "nánbiān", category: "Навигация" },
  {
    russian: "Запад",
    chinese: "西边",
    pinyin: "xībiān",
    category: "Навигация",
  },
  {
    russian: "Восток",
    chinese: "东边",
    pinyin: "dōngbiān",
    category: "Навигация",
  },
  {
    russian: "Внутри",
    chinese: "里边",
    pinyin: "lǐbiān",
    category: "Навигация",
  },
  {
    russian: "Снаружи",
    chinese: "外边",
    pinyin: "wàibiān",
    category: "Навигация",
  },
  {
    russian: "Напротив",
    chinese: "对面",
    pinyin: "duìmiàn",
    category: "Навигация",
  },
  {
    russian: "Рядом",
    chinese: "旁边",
    pinyin: "pángbiān",
    category: "Навигация",
  },
  {
    russian: "Слева",
    chinese: "左边",
    pinyin: "zuǒbiān",
    category: "Навигация",
  },
  {
    russian: "Справа",
    chinese: "右边",
    pinyin: "yòubiān",
    category: "Навигация",
  },
  {
    russian: "С обеих сторон",
    chinese: "两边",
    pinyin: "liǎngbiān",
    category: "Навигация",
  },
  {
    russian: "Посередине",
    chinese: "中间",
    pinyin: "zhōngjiān",
    category: "Навигация",
  },
  {
    russian: "От (что-то от чего-то о местонахождении)",
    chinese: "离",
    pinyin: "lí",
    category: "Навигация",
  },
  { russian: "Далеко", chinese: "远", pinyin: "yuǎn", category: "Навигация" },
  { russian: "Близко", chinese: "近", pinyin: "jìn", category: "Навигация" },
  {
    russian: "К (указание направление)",
    chinese: "向",
    pinyin: "xiàng",
    category: "Навигация",
  },
  {
    russian: "Строго (указание направления)",
    chinese: "一直",
    pinyin: "yìzhí",
    category: "Навигация",
  },
  {
    russian: "Вдоль (дороги)",
    chinese: "沿",
    pinyin: "yán",
    category: "Навигация",
  },
  {
    russian: "К (указание направления)",
    chinese: "往",
    pinyin: "wǎng",
    category: "Навигация",
  },
  {
    russian: "с(от)…до(по)",
    chinese: "从。。。到",
    pinyin: "cóng... dào",
    category: "Навигация",
  },
  { russian: "Здесь", chinese: "这里", pinyin: "zhèlǐ", category: "Навигация" },
  { russian: "Там", chinese: "哪里", pinyin: "nǎlǐ", category: "Навигация" },
  {
    russian: "Локация, местонахождение",
    chinese: "地方",
    pinyin: "dìfāng",
    category: "Навигация",
  },
  { russian: "Фамилия", chinese: "姓", pinyin: "xìng", category: "ФИО" },
  { russian: "Имя", chinese: "名字", pinyin: "míngzi", category: "ФИО" },
  { russian: "Мистер", chinese: "先生", pinyin: "xiānsheng", category: "ФИО" },
  { russian: "Мадам", chinese: "女士", pinyin: "nǚshì", category: "ФИО" },
  {
    russian: "Учитель",
    chinese: "老师",
    pinyin: "lǎoshī",
    category: "Профессии",
  },
  {
    russian: "Ученик",
    chinese: "学生",
    pinyin: "xuéshēng",
    category: "Профессии",
  },
  {
    russian: "Врач",
    chinese: "医生",
    pinyin: "yīshēng",
    category: "Профессии",
  },
  {
    russian: "Официант",
    chinese: "服务员",
    pinyin: "fúwùyuán",
    category: "Профессии",
  },
  {
    russian: "Соученик",
    chinese: "同学",
    pinyin: "tóngxué",
    category: "Профессии",
  },
  {
    russian: "Коллега",
    chinese: "同事",
    pinyin: "tóngshì",
    category: "Профессии",
  },
  {
    russian: "Инженер",
    chinese: "工程师",
    pinyin: "gōngchéngshī",
    category: "Профессии",
  },
  {
    russian: "Офисный работник",
    chinese: "职员",
    pinyin: "zhíyuán",
    category: "Профессии",
  },
  {
    russian: "Водитель",
    chinese: "司机",
    pinyin: "sījī",
    category: "Профессии",
  },
  {
    russian: "Полицейский",
    chinese: "警察",
    pinyin: "jǐngchá",
    category: "Профессии",
  },
  { russian: "Юрист", chinese: "律师", pinyin: "lǜshī", category: "Профессии" },
  {
    russian: "Актер",
    chinese: "演员",
    pinyin: "yǎnyuán",
    category: "Профессии",
  },
  { russian: "Клиент", chinese: "客户", pinyin: "kèhù", category: "Профессии" },
  {
    russian: "Начальник",
    chinese: "老板",
    pinyin: "lǎobǎn",
    category: "Профессии",
  },
  {
    russian: "Консультант",
    chinese: "营业员",
    pinyin: "yíngyèyuán",
    category: "Профессии",
  },
  {
    russian: "Наличные",
    chinese: "现金",
    pinyin: "xiànjīn",
    category: "Деньги",
  },
  {
    russian: "Кредитка",
    chinese: "信用卡",
    pinyin: "xìnyòngkǎ",
    category: "Деньги",
  },
  {
    russian: "Alipay",
    chinese: "支付宝",
    pinyin: "zhīfùbǎo",
    category: "Деньги",
  },
  { russian: "Деньги", chinese: "钱", pinyin: "qián", category: "Деньги" },
  {
    russian: "Денежная единица",
    chinese: "块",
    pinyin: "kuài",
    category: "Деньги",
  },
  { russian: "10 феней", chinese: "毛", pinyin: "máo", category: "Деньги" },
  {
    russian: "Китайская копейка",
    chinese: "分",
    pinyin: "fēn",
    category: "Деньги",
  },
  { russian: "Одежда", chinese: "衣服", pinyin: "Yifu", category: "Одежда" },
  { russian: "Ботинки", chinese: "鞋子", pinyin: "Xiezi", category: "Одежда" },
  { russian: "Штаны", chinese: "裤子", pinyin: "Kuzi", category: "Одежда" },
  {
    russian: "Платье, юбка",
    chinese: "裙子",
    pinyin: "Qunzi",
    category: "Одежда",
  },
  {
    russian: "Рубашка",
    chinese: "衬衫",
    pinyin: "Chenshan",
    category: "Одежда",
  },
  { russian: "Пальто", chinese: "外套", pinyin: "Waitao", category: "Одежда" },
  {
    russian: "Шапка, шляпа",
    chinese: "帽子",
    pinyin: "Maozi",
    category: "Одежда",
  },
  { russian: "Шарф", chinese: "围巾", pinyin: "Weijin", category: "Одежда" },
  { russian: "Свитер", chinese: "毛衣", pinyin: "Maoyi", category: "Одежда" },
  { russian: "Носки", chinese: "袜子", pinyin: "Wazi", category: "Одежда" },
  { russian: "Лицо", chinese: "脸", pinyin: "liǎn", category: "Части тела" },
  { russian: "Голова", chinese: "头", pinyin: "tóu", category: "Части тела" },
  {
    russian: "Волосы",
    chinese: "头发",
    pinyin: "tóufa",
    category: "Части тела",
  },
  {
    russian: "Глаза",
    chinese: "眼睛",
    pinyin: "yǎnjīng",
    category: "Части тела",
  },
  { russian: "Нос", chinese: "鼻子", pinyin: "bízi", category: "Части тела" },
  { russian: "Ноги", chinese: "腿", pinyin: "tuǐ", category: "Части тела" },
  { russian: "Рот", chinese: "嘴", pinyin: "zuǐ", category: "Части тела" },
  { russian: "Уши", chinese: "耳朵", pinyin: "ěrduǒ", category: "Части тела" },
  { russian: "Живот", chinese: "肚子", pinyin: "dùzi", category: "Части тела" },
  { russian: "Зубы", chinese: "牙", pinyin: "yá", category: "Части тела" },
  { russian: "Руки", chinese: "手", pinyin: "shǒu", category: "Части тела" },
  { russian: "Цвет", chinese: "颜色", pinyin: "yánsè", category: "Цвета" },
  { russian: "Синий", chinese: "蓝色", pinyin: "lán sè", category: "Цвета" },
  { russian: "Красный", chinese: "红色", pinyin: "hóng sè", category: "Цвета" },
  { russian: "Желтый", chinese: "黄色", pinyin: "huáng sè", category: "Цвета" },
  { russian: "Белый", chinese: "白色", pinyin: "bái sè", category: "Цвета" },
  { russian: "Черный", chinese: "黑色", pinyin: "hēi sè", category: "Цвета" },
  { russian: "Золотой", chinese: "金色", pinyin: "jīn sè", category: "Цвета" },
  {
    russian: "Коричневый",
    chinese: "棕色",
    pinyin: "zōng sè",
    category: "Цвета",
  },
  { russian: "Розовый", chinese: "粉色", pinyin: "fěn sè", category: "Цвета" },
  {
    russian: "Баскетбол",
    chinese: "篮球",
    pinyin: "lánqiú",
    category: "Спорт",
  },
  { russian: "Волейбол", chinese: "排球", pinyin: "páiqiú", category: "Спорт" },
  {
    russian: "Пингпонг",
    chinese: "乒乓球",
    pinyin: "pīngpāngqiú",
    category: "Спорт",
  },
  { russian: "Теннис", chinese: "网球", pinyin: "wǎngqiú", category: "Спорт" },
  { russian: "Футбол", chinese: "足球", pinyin: "zúqiú", category: "Спорт" },
  { russian: "Бейсбол", chinese: "棒球", pinyin: "bàngqiú", category: "Спорт" },
  {
    russian: "Бадминтон",
    chinese: "羽毛球",
    pinyin: "yǔmáoqiú",
    category: "Спорт",
  },
  {
    russian: "Велосипед",
    chinese: "自行车",
    pinyin: "zìxíngchē",
    category: "Спорт",
  },
  {
    russian: "Мотоцикл",
    chinese: "摩托车",
    pinyin: "mótuōchē",
    category: "Транспорт",
  },
  {
    russian: "Самолет",
    chinese: "飞机",
    pinyin: "fēijī",
    category: "Транспорт",
  },
  {
    russian: "Поезд",
    chinese: "火车",
    pinyin: "huǒchē",
    category: "Транспорт",
  },
  { russian: "Лодка", chinese: "船", pinyin: "chuán", category: "Транспорт" },
  {
    russian: "Такси",
    chinese: "出租车",
    pinyin: "chūzūchē",
    category: "Транспорт",
  },
  { russian: "Метро", chinese: "地铁", pinyin: "dìtiě", category: "Транспорт" },
  {
    russian: "Автобус",
    chinese: "公交车",
    pinyin: "Gongjiaoche",
    category: "Транспорт",
  },
  {
    russian: "Стол",
    chinese: "桌子",
    pinyin: "Zhuozi",
    category: "Существительные",
  },
  {
    russian: "Кровать",
    chinese: "床",
    pinyin: "Chuang",
    category: "Существительные",
  },
  {
    russian: "Книга",
    chinese: "书",
    pinyin: "Shu",
    category: "Существительные",
  },
  {
    russian: "Телевизор",
    chinese: "电视",
    pinyin: "Dianshi",
    category: "Существительные",
  },
  {
    russian: "Фильм",
    chinese: "电影",
    pinyin: "Dianying",
    category: "Существительные",
  },
  {
    russian: "Музыка",
    chinese: "音乐",
    pinyin: "Yinyue",
    category: "Существительные",
  },
  {
    russian: "Игра",
    chinese: "游戏",
    pinyin: "Youxi",
    category: "Существительные",
  },
  {
    russian: "Газета",
    chinese: "报纸",
    pinyin: "Baozhi",
    category: "Существительные",
  },
  {
    russian: "Мобильник",
    chinese: "手机",
    pinyin: "Shouji",
    category: "Существительные",
  },
  {
    russian: "Часы наручные",
    chinese: "手表",
    pinyin: "Shoubiao",
    category: "Существительные",
  },
  {
    russian: "Сумка",
    chinese: "包",
    pinyin: "Bao",
    category: "Существительные",
  },
  {
    russian: "Школьный рюкзак",
    chinese: "书包",
    pinyin: "Shubao",
    category: "Существительные",
  },
  {
    russian: "Очки",
    chinese: "眼镜",
    pinyin: "Yanjing",
    category: "Существительные",
  },
  {
    russian: "Цветы",
    chinese: "花",
    pinyin: "Hua",
    category: "Существительные",
  },
  {
    russian: "Лампа, свет",
    chinese: "灯",
    pinyin: "Deng",
    category: "Существительные",
  },
  {
    russian: "Компьютер",
    chinese: "电脑",
    pinyin: "Diannao",
    category: "Существительные",
  },
  {
    russian: "Кошелек",
    chinese: "钱包",
    pinyin: "Qianbao",
    category: "Существительные",
  },
  {
    russian: "Песня",
    chinese: "歌",
    pinyin: "Ge",
    category: "Существительные",
  },
  {
    russian: "Дорога",
    chinese: "路",
    pinyin: "Lu",
    category: "Существительные",
  },
  {
    russian: "Перекресток",
    chinese: "路口",
    pinyin: "Lukou",
    category: "Существительные",
  },
  {
    russian: "Домашняя работа",
    chinese: "作业",
    pinyin: "Zuoye",
    category: "Существительные",
  },
  {
    russian: "Письмо",
    chinese: "信",
    pinyin: "Xin",
    category: "Существительные",
  },
  {
    russian: "Билет",
    chinese: "票",
    pinyin: "Piao",
    category: "Существительные",
  },
  {
    russian: "Станция",
    chinese: "站",
    pinyin: "Zhan",
    category: "Существительные",
  },
  {
    russian: "Лекарство",
    chinese: "药",
    pinyin: "Yao",
    category: "Существительные",
  },
  {
    russian: "Договор",
    chinese: "合同",
    pinyin: "Hetong",
    category: "Существительные",
  },
  {
    russian: "Документ",
    chinese: "文件",
    pinyin: "Wenjian",
    category: "Существительные",
  },
  {
    russian: "Ручка",
    chinese: "笔",
    pinyin: "Bi",
    category: "Существительные",
  },
  {
    russian: "Визитка",
    chinese: "名片",
    pinyin: "Mingpian",
    category: "Существительные",
  },
  {
    russian: "Пекинская опера",
    chinese: "京剧",
    pinyin: "Jingju",
    category: "Существительные",
  },
  {
    russian: "Каллиграфия",
    chinese: "书法",
    pinyin: "Shufa",
    category: "Существительные",
  },
  {
    russian: "Подарок",
    chinese: "礼物",
    pinyin: "Liwu",
    category: "Существительные",
  },
  {
    russian: "Дверь",
    chinese: "门",
    pinyin: "Men",
    category: "Существительные",
  },
  {
    russian: "Телефон",
    chinese: "电话",
    pinyin: "Dianhua",
    category: "Существительные",
  },
  {
    russian: "Словарь",
    chinese: "词典",
    pinyin: "Cidian",
    category: "Существительные",
  },
  {
    russian: "Комната",
    chinese: "房间",
    pinyin: "Fangjian",
    category: "Существительные",
  },
  {
    russian: "Спальня",
    chinese: "卧室",
    pinyin: "Woshi",
    category: "Существительные",
  },
  {
    russian: "Кухня",
    chinese: "厨房",
    pinyin: "Chufang",
    category: "Существительные",
  },
  {
    russian: "Ванная комната",
    chinese: "卫生间",
    pinyin: "Weishengjian",
    category: "Существительные",
  },
  {
    russian: "Гостиная",
    chinese: "客厅",
    pinyin: "Keting",
    category: "Существительные",
  },
  {
    russian: "Стул",
    chinese: "椅子",
    pinyin: "Yizi",
    category: "Существительные",
  },
  {
    russian: "Холодильник",
    chinese: "冰箱",
    pinyin: "Bingxiang",
    category: "Существительные",
  },
  {
    russian: "Шкаф",
    chinese: "柜子",
    pinyin: "Guizi",
    category: "Существительные",
  },
  {
    russian: "Фотография",
    chinese: "照片",
    pinyin: "Zhaopian",
    category: "Существительные",
  },
  {
    russian: "Стена",
    chinese: "墙",
    pinyin: "Qiang",
    category: "Существительные",
  },
  {
    russian: "Смска",
    chinese: "短信",
    pinyin: "Duanxin",
    category: "Существительные",
  },
  {
    russian: "Электронное сообщение",
    chinese: "邮件",
    pinyin: "Youjian",
    category: "Существительные",
  },
  {
    russian: "Вичат",
    chinese: "微信",
    pinyin: "Weixin",
    category: "Существительные",
  },
  {
    russian: "Всякое разное",
    chinese: "东西",
    pinyin: "Dongxi",
    category: "Существительные",
  },
  {
    russian: "Иероглифы",
    chinese: "汉字",
    pinyin: "Hanzi",
    category: "Существительные",
  },
  {
    russian: "Лифт",
    chinese: "电梯",
    pinyin: "Dianti",
    category: "Существительные",
  },
  {
    russian: "Меню",
    chinese: "菜单",
    pinyin: "Caidan",
    category: "Существительные",
  },
  {
    russian: "Манеры, отношение",
    chinese: "态度",
    pinyin: "Taidu",
    category: "Существительные",
  },
  {
    russian: "Вкус",
    chinese: "味道",
    pinyin: "Weidao",
    category: "Существительные",
  },
  {
    russian: "Окно",
    chinese: "窗户",
    pinyin: "chuānghù",
    category: "Существительные",
  },
  {
    russian: "Багаж",
    chinese: "行李",
    pinyin: "xínglǐ",
    category: "Существительные",
  },
  {
    russian: "Место / сиденье",
    chinese: "座位",
    pinyin: "zuòwèi",
    category: "Существительные",
  },
  {
    russian: "Культура",
    chinese: "文化",
    pinyin: "wénhuà",
    category: "Существительные",
  },
  {
    russian: "Университет, колледж",
    chinese: "大学",
    pinyin: "dàxué",
    category: "Существительные",
  },
  {
    russian: "Учебный год/класс",
    chinese: "年级",
    pinyin: "niánjí",
    category: "Существительные",
  },
  {
    russian: "Специальность",
    chinese: "专业",
    pinyin: "zhuānyè",
    category: "Существительные",
  },
  {
    russian: "Экономика",
    chinese: "经济",
    pinyin: "jīngjì",
    category: "Существительные",
  },
  {
    russian: "История",
    chinese: "历史",
    pinyin: "lìshǐ",
    category: "Существительные",
  },
  {
    russian: "Право",
    chinese: "法律",
    pinyin: "fǎlǜ",
    category: "Существительные",
  },
  {
    russian: "Учебное помещение, класс, аудитория",
    chinese: "教室",
    pinyin: "jiàoshì",
    category: "Существительные",
  },
  {
    russian: "Столовая",
    chinese: "食堂",
    pinyin: "shítáng",
    category: "Существительные",
  },
  {
    russian: "Зимние каникулы",
    chinese: "寒假",
    pinyin: "hánjià",
    category: "Существительные",
  },
  {
    russian: "Летние каникулы",
    chinese: "暑假",
    pinyin: "shǔjià",
    category: "Существительные",
  },
  {
    russian: "Знак зодиака",
    chinese: "属",
    pinyin: "shǔ",
    category: "Существительные",
  },
  {
    russian: "Город",
    chinese: "城市",
    pinyin: "chéngshì",
    category: "Существительные",
  },
  {
    russian: "Дракон",
    chinese: "龙",
    pinyin: "lóng",
    category: "Существительные",
  },
  {
    russian: "Хороший",
    chinese: "好",
    pinyin: "Hao",
    category: "Прилагательные",
  },
  {
    russian: "Плохой",
    chinese: "差",
    pinyin: "Cha",
    category: "Прилагательные",
  },
  {
    russian: "Большой",
    chinese: "大",
    pinyin: "Da",
    category: "Прилагательные",
  },
  {
    russian: "Маленький",
    chinese: "小",
    pinyin: "Xiao",
    category: "Прилагательные",
  },
  {
    russian: "Дорогой",
    chinese: "贵",
    pinyin: "Gui",
    category: "Прилагательные",
  },
  {
    russian: "Дешевый",
    chinese: "便宜",
    pinyin: "Pianyi",
    category: "Прилагательные",
  },
  {
    russian: "Холодный",
    chinese: "冷",
    pinyin: "Leng",
    category: "Прилагательные",
  },
  {
    russian: "Горячий",
    chinese: "热",
    pinyin: "Re",
    category: "Прилагательные",
  },
  {
    russian: "Голодный",
    chinese: "饿",
    pinyin: "E",
    category: "Прилагательные",
  },
  {
    russian: "Испытывающий жажду",
    chinese: "渴",
    pinyin: "Ke",
    category: "Прилагательные",
  },
  {
    russian: "Вкусный о еде",
    chinese: "好吃",
    pinyin: "Haochi",
    category: "Прилагательные",
  },
  {
    russian: "Вкусный о питье",
    chinese: "好喝",
    pinyin: "Haohe",
    category: "Прилагательные",
  },
  {
    russian: "Красивый",
    chinese: "好看",
    pinyin: "Haokan",
    category: "Прилагательные",
  },
  {
    russian: "Чистый",
    chinese: "干净",
    pinyin: "Ganjing",
    category: "Прилагательные",
  },
  {
    russian: "Прекрасный",
    chinese: "漂亮",
    pinyin: "Piaoliang",
    category: "Прилагательные",
  },
  {
    russian: "Новый",
    chinese: "新",
    pinyin: "Xin",
    category: "Прилагательные",
  },
  {
    russian: "Старый",
    chinese: "旧",
    pinyin: "Jiu",
    category: "Прилагательные",
  },
  {
    russian: "Тесный (толпа)",
    chinese: "挤",
    pinyin: "Ji",
    category: "Прилагательные",
  },
  {
    russian: "Удобный, подходящий",
    chinese: "方便",
    pinyin: "Fangbian",
    category: "Прилагательные",
  },
  {
    russian: "Хорошо себя чувствующий",
    chinese: "舒服",
    pinyin: "Shufu",
    category: "Прилагательные",
  },
  {
    russian: "Занятый",
    chinese: "忙",
    pinyin: "Mang",
    category: "Прилагательные",
  },
  {
    russian: "Уставший",
    chinese: "累",
    pinyin: "Lei",
    category: "Прилагательные",
  },
  {
    russian: "Бедный",
    chinese: "穷",
    pinyin: "Qiong",
    category: "Прилагательные",
  },
  {
    russian: "Свободный",
    chinese: "轻松",
    pinyin: "Qingsong",
    category: "Прилагательные",
  },
  {
    russian: "Богатый",
    chinese: "有钱",
    pinyin: "Youqian",
    category: "Прилагательные",
  },
  {
    russian: "Странный",
    chinese: "奇怪",
    pinyin: "Qiguai",
    category: "Прилагательные",
  },
  {
    russian: "Интересный",
    chinese: "有意思",
    pinyin: "Youyisi",
    category: "Прилагательные",
  },
  {
    russian: "Сладкий",
    chinese: "甜",
    pinyin: "Tian",
    category: "Прилагательные",
  },
  {
    russian: "Горький",
    chinese: "苦",
    pinyin: "Ku",
    category: "Прилагательные",
  },
  {
    russian: "Кислый",
    chinese: "酸",
    pinyin: "Suan",
    category: "Прилагательные",
  },
  {
    russian: "Соленый",
    chinese: "咸",
    pinyin: "Xian",
    category: "Прилагательные",
  },
  {
    russian: "Острый",
    chinese: "辣",
    pinyin: "La",
    category: "Прилагательные",
  },
  {
    russian: "Длинный",
    chinese: "长",
    pinyin: "Chang",
    category: "Прилагательные",
  },
  {
    russian: "Короткий",
    chinese: "短",
    pinyin: "Duan",
    category: "Прилагательные",
  },
  {
    russian: "Высокий",
    chinese: "高",
    pinyin: "Gao",
    category: "Прилагательные",
  },
  {
    russian: "Низкий",
    chinese: "矮",
    pinyin: "Ai",
    category: "Прилагательные",
  },
  {
    russian: "Толстый",
    chinese: "胖",
    pinyin: "Pang",
    category: "Прилагательные",
  },
  {
    russian: "Худой",
    chinese: "瘦",
    pinyin: "Shou",
    category: "Прилагательные",
  },
  {
    russian: "Классный",
    chinese: "帅",
    pinyin: "Shuai",
    category: "Прилагательные",
  },
  {
    russian: "Милый",
    chinese: "可爱",
    pinyin: "Keai",
    category: "Прилагательные",
  },
  {
    russian: "Умный",
    chinese: "聪明",
    pinyin: "Congming",
    category: "Прилагательные",
  },
  {
    russian: "Свежий",
    chinese: "新鲜",
    pinyin: "Xinxian",
    category: "Прилагательные",
  },
  {
    russian: "Грязный",
    chinese: "脏",
    pinyin: "Zang",
    category: "Прилагательные",
  },
  {
    russian: "Послушный",
    chinese: "听话",
    pinyin: "Tinghua",
    category: "Прилагательные",
  },
  {
    russian: "Хороший (о животном)",
    chinese: "乖",
    pinyin: "Guai",
    category: "Прилагательные",
  },
  {
    russian: "Ленивый",
    chinese: "懒",
    pinyin: "Lan",
    category: "Прилагательные",
  },
  {
    russian: "Глупый",
    chinese: "傻",
    pinyin: "Sha",
    category: "Прилагательные",
  },
  {
    russian: "Уродливый",
    chinese: "丑",
    pinyin: "Chou",
    category: "Прилагательные",
  },
  {
    russian: "Сонный",
    chinese: "困",
    pinyin: "Kun",
    category: "Прилагательные",
  },
  {
    russian: "Сытый",
    chinese: "饱",
    pinyin: "Bao",
    category: "Прилагательные",
  },
  {
    russian: "Известный",
    chinese: "有名",
    pinyin: "Youming",
    category: "Прилагательные",
  },
  {
    russian: "Горячий (кипящий)",
    chinese: "烫",
    pinyin: "Tang",
    category: "Прилагательные",
  },
  {
    russian: "Оживленный",
    chinese: "热闹",
    pinyin: "Renao",
    category: "Прилагательные",
  },
  {
    russian: "Тупой (глупый)",
    chinese: "笨",
    pinyin: "bèn",
    category: "Прилагательные",
  },
  {
    russian: "Старый",
    chinese: "老",
    pinyin: "lǎo",
    category: "Прилагательные",
  },
  {
    russian: "Молодой",
    chinese: "年轻",
    pinyin: "niánqīng",
    category: "Прилагательные",
  },
  {
    russian: "Страдающий",
    chinese: "伤心",
    pinyin: "Shangxin",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Испуганный",
    chinese: "害怕",
    pinyin: "Haipa",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Переживающий",
    chinese: "担心",
    pinyin: "Danxin",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Тоскующий",
    chinese: "郁闷",
    pinyin: "Yumen",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Грустый",
    chinese: "难过",
    pinyin: "Nanguo",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Веселый",
    chinese: "高兴",
    pinyin: "Gaoxing",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Сложный",
    chinese: "难",
    pinyin: "nán",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Простой",
    chinese: "简单",
    pinyin: "jiǎndān",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Нервный, взволнованный",
    chinese: "紧张",
    pinyin: "jǐnzhāng",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Злой",
    chinese: "生气",
    pinyin: "shēngqì",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Счастливый",
    chinese: "开心",
    pinyin: "kāixīn",
    category: "Прилагательные (эмоции)",
  },
  {
    russian: "Часто",
    chinese: "常常",
    pinyin: "Changchang",
    category: "Наречия",
  },
  {
    russian: "Часто",
    chinese: "经常",
    pinyin: "Jingchang",
    category: "Наречия",
  },
  {
    russian: "Сразу же",
    chinese: "马上",
    pinyin: "Mashang",
    category: "Наречия",
  },
  { russian: "Очень", chinese: "很", pinyin: "Hen", category: "Наречия" },
  {
    russian: "Чрезвычайно",
    chinese: "非常",
    pinyin: "Feichang",
    category: "Наречия",
  },
  {
    russian: "Особенно",
    chinese: "特别",
    pinyin: "Tebie",
    category: "Наречия",
  },
  {
    russian: "Так (слишком)",
    chinese: "太…了",
    pinyin: "Tai…le",
    category: "Наречия",
  },
  {
    russian: "Реально, действительно",
    chinese: "真",
    pinyin: "Zhen",
    category: "Наречия",
  },
  {
    russian: "Немного (в негативном значении)",
    chinese: "有点儿",
    pinyin: "Youdianr",
    category: "Наречия",
  },
  {
    russian: "Немного (при сравнении)",
    chinese: "一点儿",
    pinyin: "Yidianr",
    category: "Наречия",
  },
  {
    russian: "Обычно",
    chinese: "平时",
    pinyin: "Pingshi",
    category: "Наречия",
  },
  { russian: "Всегда", chinese: "一直", pinyin: "Yizhi", category: "Наречия" },
  { russian: "Быстро", chinese: "快", pinyin: "Kuai", category: "Наречия" },
  { russian: "Медленно", chinese: "慢", pinyin: "Man", category: "Наречия" },
  { russian: "Рано", chinese: "早", pinyin: "Zao", category: "Наречия" },
  { russian: "Поздно", chinese: "晚", pinyin: "Wan", category: "Наречия" },
  { russian: "Уже", chinese: "已经", pinyin: "Yijing", category: "Наречия" },
  {
    russian: "Только что",
    chinese: "刚才",
    pinyin: "Gangcai",
    category: "Наречия",
  },
  {
    russian: "Одновременно",
    chinese: "一边",
    pinyin: "Yibian",
    category: "Наречия",
  },
  {
    russian: "Иногда",
    chinese: "有时候",
    pinyin: "Youshihou",
    category: "Наречия",
  },
  {
    russian: "В то время как",
    chinese: "的时候",
    pinyin: "Deshihou",
    category: "Наречия",
  },
  {
    russian: "Несколько (немного) времени",
    chinese: "一会儿",
    pinyin: "Yihuir",
    category: "Наречия",
  },
  {
    russian: "Несколько (немного) о количестве",
    chinese: "几",
    pinyin: "ji",
    category: "Наречия",
  },
  {
    russian: "Так, так сильно",
    chinese: "这么",
    pinyin: "zhème",
    category: "Наречия",
  },
  {
    russian: "Сравнительная степень (что-то) чем (что-то)",
    chinese: "比",
    pinyin: "Bi",
    category: "Сравнительная степень",
  },
  {
    russian: "Сравнительная степень (не такой как)",
    chinese: "没有",
    pinyin: "Meiyou",
    category: "Сравнительная степень",
  },
  {
    russian: "Сравнительная степень (еще более…)",
    chinese: "更",
    pinyin: "Geng",
    category: "Сравнительная степень",
  },
  {
    russian: "Самый",
    chinese: "最",
    pinyin: "Zui",
    category: "Сравнительная степень",
  },
  {
    russian: "Такое же",
    chinese: "一样",
    pinyin: "Yiyang",
    category: "Сравнительная степень",
  },
  {
    russian: "Все более и более",
    chinese: "越来越",
    pinyin: "Yuelauyue",
    category: "Сравнительная степень",
  },
  {
    russian: "Не (настоящее и будущее)",
    chinese: "不",
    pinyin: "Bu",
    category: "Вспомогательные слова",
  },
  {
    russian: "Не (прошедшее и продолжающееся, с глаголом “иметь”)",
    chinese: "没",
    pinyin: "Mei",
    category: "Вспомогательные слова",
  },
  {
    russian: "Это",
    chinese: "这",
    pinyin: "Zhe",
    category: "Вспомогательные слова",
  },
  {
    russian: "То",
    chinese: "那",
    pinyin: "Na",
    category: "Вспомогательные слова",
  },
  {
    russian: "Тоже",
    chinese: "也",
    pinyin: "Ye",
    category: "Вспомогательные слова",
  },
  {
    russian: "Все, оба",
    chinese: "都",
    pinyin: "Dou",
    category: "Вспомогательные слова",
  },
  {
    russian: "Частица принадлежности, утвердительная форма",
    chinese: "的",
    pinyin: "De",
    category: "Вспомогательные слова",
  },
  {
    russian: "этот, эти",
    chinese: "这个",
    pinyin: "Zhege",
    category: "Вспомогательные слова",
  },
  {
    russian: "Следующий",
    chinese: "下个",
    pinyin: "Xiage",
    category: "Вспомогательные слова",
  },
  {
    russian: "Предыдущий",
    chinese: "上个",
    pinyin: "Shangge",
    category: "Вспомогательные слова",
  },
  {
    russian: "Вместе",
    chinese: "一起",
    pinyin: "Yiqi",
    category: "Вспомогательные слова",
  },
  {
    russian: "И, с",
    chinese: "和",
    pinyin: "He",
    category: "Вспомогательные слова",
  },
  {
    russian: "С (кем-то)",
    chinese: "跟",
    pinyin: "Gen",
    category: "Вспомогательные слова",
  },
  {
    russian: "Также, тоже",
    chinese: "还",
    pinyin: "Hai",
    category: "Вспомогательные слова",
  },
  {
    russian: "Или (в вопросах)",
    chinese: "还是",
    pinyin: "Haishi",
    category: "Вспомогательные слова",
  },
  {
    russian: "Или (в утвердительных)",
    chinese: "或者",
    pinyin: "Huozhe",
    category: "Вспомогательные слова",
  },
  {
    russian: "Суффикс продолжающегося действия",
    chinese: "着",
    pinyin: "Zhe",
    category: "Вспомогательные слова",
  },
  {
    russian: "Суффикс завершенного действия (present perfect)",
    chinese: "过",
    pinyin: "Guo",
    category: "Вспомогательные слова",
  },
  {
    russian: "Добавляется к глаголам чтобы показать результат",
    chinese: "到",
    pinyin: "Dao",
    category: "Вспомогательные слова",
  },
  {
    russian: "Соединительная частица глаголов и наречий",
    chinese: "得",
    pinyin: "De",
    category: "Вспомогательные слова",
  },
  {
    russian:
      "Обозначает, что действие происходит в какой-то момент (present continuous)",
    chinese: "正在",
    pinyin: "Zhengzai",
    category: "Вспомогательные слова",
  },
  {
    russian: "Дательный падеж",
    chinese: "给",
    pinyin: "Gei",
    category: "Вспомогательные слова",
  },
  {
    russian: "Наверное",
    chinese: "可能",
    pinyin: "Keneng",
    category: "Вспомогательные слова",
  },
  {
    russian: "Запрет /совет что-то не делать",
    chinese: "别",
    pinyin: "Bie",
    category: "Вспомогательные слова",
  },
  {
    russian: "Если",
    chinese: "如果",
    pinyin: "Ruguo",
    category: "Вспомогательные слова",
  },
  {
    russian: "То (после если)",
    chinese: "就",
    pinyin: "Jiu",
    category: "Вспомогательные слова",
  },
  {
    russian: "Сначала",
    chinese: "先",
    pinyin: "Xian",
    category: "Вспомогательные слова",
  },
  {
    russian: "Потом",
    chinese: "然后",
    pinyin: "Ranhou",
    category: "Вспомогательные слова",
  },
  {
    russian: "Еще раз, потом",
    chinese: "再",
    pinyin: "Zai",
    category: "Вспомогательные слова",
  },
  {
    russian: "Винительный падеж",
    chinese: "把",
    pinyin: "Ba",
    category: "Вспомогательные слова",
  },
  {
    russian: "Итого",
    chinese: "一共",
    pinyin: "Yigong",
    category: "Вспомогательные слова",
  },
  {
    russian: "Но",
    chinese: "可是",
    pinyin: "Keshi",
    category: "Вспомогательные слова",
  },
  {
    russian: "Поэтому",
    chinese: "所以",
    pinyin: "Suoyi",
    category: "Вспомогательные слова",
  },
  {
    russian: "Помимо",
    chinese: "除了",
    pinyin: "Chule",
    category: "Вспомогательные слова",
  },
  {
    russian: "Образует пассивную форму",
    chinese: "被",
    pinyin: "Bei",
    category: "Вспомогательные слова",
  },
  {
    russian: "Потому что",
    chinese: "因为",
    pinyin: "Yinwei",
    category: "Вспомогательные слова",
  },
  {
    russian: "Конечно",
    chinese: "当然",
    pinyin: "dāngrán",
    category: "Вспомогательные слова",
  },
  {
    russian: "Только",
    chinese: "只",
    pinyin: "zhǐ",
    category: "Вспомогательные слова",
  },
  {
    russian: "Чтобы (для того чтобы)",
    chinese: "为了",
    pinyin: "wèile",
    category: "Вспомогательные слова",
  },
  {
    russian: "Придает глаголу «легкость» (например, открыть-->приоткрыть)",
    chinese: "一下",
    pinyin: "yīxià",
    category: "Вспомогательные слова",
  },
  {
    russian: "Частица, превращающая прилагательное в наречие",
    chinese: "地",
    pinyin: "de",
    category: "Вспомогательные слова",
  },
  {
    russian: "Указывает причину",
    chinese: "为",
    pinyin: "wèi",
    category: "Вспомогательные слова",
  },
  {
    russian: "Не делай чего-то (совет, указание)",
    chinese: "不要",
    pinyin: "bùyào",
    category: "Вспомогательные слова",
  },
  {
    russian: "Вопросительная частица",
    chinese: "吗",
    pinyin: "Ma",
    category: "Вопросы",
  },
  { russian: "Что", chinese: "什么", pinyin: "Shenme", category: "Вопросы" },
  { russian: "Кто", chinese: "谁", pinyin: "Shei", category: "Вопросы" },
  { russian: "А (ты)?", chinese: "呢", pinyin: "Ne", category: "Вопросы" },
  { russian: "Где", chinese: "哪里", pinyin: "Nali", category: "Вопросы" },
  {
    russian: "Сколько (про маленькое количество – до 5-9)",
    chinese: "几",
    pinyin: "Ji",
    category: "Вопросы",
  },
  {
    russian: "Сколько",
    chinese: "多少",
    pinyin: "Duoshao",
    category: "Вопросы",
  },
  {
    russian: "Сколько лет",
    chinese: "多大",
    pinyin: "Duoda",
    category: "Вопросы",
  },
  {
    russian: "Как долго",
    chinese: "多久",
    pinyin: "Duojiu",
    category: "Вопросы",
  },
  {
    russian: "Какой, какая, какое",
    chinese: "哪",
    pinyin: "Na",
    category: "Вопросы",
  },
  {
    russian: "Что делаешь",
    chinese: "干什么",
    pinyin: "Ganshenme",
    category: "Вопросы",
  },
  {
    russian: "Когда",
    chinese: "什么时候",
    pinyin: "Shenmeshihou",
    category: "Вопросы",
  },
  { russian: "Как", chinese: "怎么", pinyin: "Zenme", category: "Вопросы" },
  {
    russian: "Как (как тебе)",
    chinese: "怎么样",
    pinyin: "Zenmeyang",
    category: "Вопросы",
  },
  {
    russian: "Частица формирующая предположения",
    chinese: "吧",
    pinyin: "Ba",
    category: "Вопросы",
  },
  {
    russian: "Почему",
    chinese: "为什么",
    pinyin: "Weishenme",
    category: "Вопросы",
  },
  {
    russian: "Хорошо?",
    chinese: "行吗",
    pinyin: "Xing ma",
    category: "Вопросы",
  },
  {
    russian: "Китай",
    chinese: "中国",
    pinyin: "Zhongguo",
    category: "География",
  },
  {
    russian: "Америка",
    chinese: "美国",
    pinyin: "Meiguo",
    category: "География",
  },
  {
    russian: "Россия",
    chinese: "俄罗斯",
    pinyin: "Eluosi",
    category: "География",
  },
  {
    russian: "Англия",
    chinese: "英国",
    pinyin: "Yingguo",
    category: "География",
  },
  {
    russian: "Тайланд",
    chinese: "泰国",
    pinyin: "Taiguo",
    category: "География",
  },
  {
    russian: "Франция",
    chinese: "法国",
    pinyin: "Faguo",
    category: "География",
  },
  {
    russian: "Германия",
    chinese: "德国",
    pinyin: "Deguo",
    category: "География",
  },
  {
    russian: "Шанхай",
    chinese: "上海",
    pinyin: "Shanghai",
    category: "География",
  },
  {
    russian: "Пекин",
    chinese: "北京",
    pinyin: "Beijing",
    category: "География",
  },
  {
    russian: "Гонконг",
    chinese: "香港",
    pinyin: "Xianggang",
    category: "География",
  },
  {
    russian: "Китайский язык",
    chinese: "汉语",
    pinyin: "Hanyu",
    category: "География",
  },
  {
    russian: "Английский язык",
    chinese: "英语",
    pinyin: "Yingyu",
    category: "География",
  },
  {
    russian: "Казань",
    chinese: "喀山",
    pinyin: "kāshān",
    category: "География",
  },
  { russian: "Привет", chinese: "你好", pinyin: "Nihao", category: "Общение" },
  { russian: "Пока", chinese: "再见", pinyin: "Zaijian", category: "Общение" },
  {
    russian: "Спасибо",
    chinese: "谢谢",
    pinyin: "Xiexie",
    category: "Общение",
  },
  {
    russian: "Большое спасибо",
    chinese: "多谢",
    pinyin: "Duoxie",
    category: "Общение",
  },
  {
    russian: "Пожалуйста (в ответ на спасибо)",
    chinese: "不客气",
    pinyin: "Bukeqi",
    category: "Общение",
  },
  {
    russian: "Извините",
    chinese: "对不起",
    pinyin: "Duibuqi",
    category: "Общение",
  },
  {
    russian: "Пожалуйста (при просьбе)",
    chinese: "请",
    pinyin: "Qing",
    category: "Общение",
  },
  {
    russian: "Извините (при просьбе)",
    chinese: "请问",
    pinyin: "Qingwen",
    category: "Общение",
  },
  {
    russian: "Не стоит переживать",
    chinese: "没关系",
    pinyin: "Meiguanxi",
    category: "Общение",
  },
  { russian: "Алё", chinese: "喂", pinyin: "Wei", category: "Общение" },
  {
    russian: "Рад знакомству",
    chinese: "幸会",
    pinyin: "xìnghuì",
    category: "Общение",
  },
  { russian: "0", chinese: "零", pinyin: "Ling", category: "Цифры" },
  { russian: "1", chinese: "一", pinyin: "Yi", category: "Цифры" },
  { russian: "2", chinese: "两", pinyin: "Liang", category: "Цифры" },
  { russian: "2", chinese: "二", pinyin: "Er", category: "Цифры" },
  { russian: "3", chinese: "三", pinyin: "San", category: "Цифры" },
  { russian: "4", chinese: "四", pinyin: "Si", category: "Цифры" },
  { russian: "5", chinese: "五", pinyin: "Wu", category: "Цифры" },
  { russian: "6", chinese: "六", pinyin: "Liu", category: "Цифры" },
  { russian: "7", chinese: "七", pinyin: "Qi", category: "Цифры" },
  { russian: "8", chinese: "八", pinyin: "Ba", category: "Цифры" },
  { russian: "9", chinese: "九", pinyin: "Jiu", category: "Цифры" },
  { russian: "10", chinese: "十", pinyin: "Shi", category: "Цифры" },
  { russian: "100", chinese: "百", pinyin: "Bai", category: "Цифры" },
  { russian: "1000", chinese: "千", pinyin: "Qian", category: "Цифры" },
  { russian: "10000", chinese: "万", pinyin: "Wan", category: "Цифры" },
  { russian: "100000000", chinese: "亿", pinyin: "Yi", category: "Цифры" },
];

export { wordList };
