let wordListVerbs = [
  { russian: "Быть", chinese: "是", pinyin: "shì", category: "Глаголы" },
  { russian: "Иметь", chinese: "有", pinyin: "yǒu", category: "Глаголы" },
  { russian: "Любить", chinese: "爱", pinyin: "ài", category: "Глаголы" },
  {
    russian: "Нравиться",
    chinese: "喜欢",
    pinyin: "xǐhuān",
    category: "Глаголы",
  },
  { russian: "Есть", chinese: "吃", pinyin: "chī", category: "Глаголы" },
  {
    russian: "Есть еду",
    chinese: "吃饭",
    pinyin: "chīfàn",
    category: "Глаголы",
  },
  { russian: "Пить", chinese: "喝", pinyin: "hē", category: "Глаголы" },
  {
    russian: "Звать, называть",
    chinese: "叫",
    pinyin: "jiào",
    category: "Глаголы",
  },
  { russian: "Говорить", chinese: "说", pinyin: "shuō", category: "Глаголы" },
  {
    russian: "Разговаривать",
    chinese: "说话",
    pinyin: "shuōhuà",
    category: "Глаголы",
  },
  {
    russian: "Разговаривать (неформ.)",
    chinese: "聊天",
    pinyin: "liáotiān",
    category: "Глаголы",
  },
  { russian: "Учить", chinese: "学", pinyin: "xué", category: "Глаголы" },
  { russian: "Изучать", chinese: "学习", pinyin: "xuéxí", category: "Глаголы" },
  { russian: "Покупать", chinese: "买", pinyin: "mǎi", category: "Глаголы" },
  { russian: "Продавать", chinese: "卖", pinyin: "mài", category: "Глаголы" },
  { russian: "Хотеть", chinese: "想", pinyin: "xiǎng", category: "Глаголы" },
  {
    russian: "Хотеть, нуждаться",
    chinese: "要",
    pinyin: "yào",
    category: "Глаголы",
  },
  { russian: "Давать", chinese: "给", pinyin: "gěi", category: "Глаголы" },
  { russian: "Идти", chinese: "去", pinyin: "qù", category: "Глаголы" },
  { russian: "Находиться", chinese: "在", pinyin: "zài", category: "Глаголы" },
  { russian: "Мыть", chinese: "洗", pinyin: "xǐ", category: "Глаголы" },
  {
    russian: "Принимать душ, купаться",
    chinese: "洗澡",
    pinyin: "xǐzǎo",
    category: "Глаголы",
  },
  {
    russian: "Умываться",
    chinese: "洗脸",
    pinyin: "xǐliǎn",
    category: "Глаголы",
  },
  {
    russian: "Вставать с постели",
    chinese: "起床",
    pinyin: "qǐchuáng",
    category: "Глаголы",
  },
  {
    russian: "Начинать работу",
    chinese: "上班",
    pinyin: "shàngbān",
    category: "Глаголы",
  },
  {
    russian: "Заканчивать работу",
    chinese: "下班",
    pinyin: "xiàbān",
    category: "Глаголы",
  },
  {
    russian: "Чистить зубы",
    chinese: "刷牙",
    pinyin: "shuāyá",
    category: "Глаголы",
  },
  {
    russian: "Начинать учебу, занятие",
    chinese: "上课",
    pinyin: "shàngkè",
    category: "Глаголы",
  },
  {
    russian: "Заказчивать учебу, занятие",
    chinese: "下课",
    pinyin: "xiàkè",
    category: "Глаголы",
  },
  {
    russian: "Смотреть/читать",
    chinese: "看",
    pinyin: "kàn",
    category: "Глаголы",
  },
  {
    russian: "Видеть",
    chinese: "看见",
    pinyin: "kànjiàn",
    category: "Глаголы",
  },
  {
    russian: "Делать/готовить",
    chinese: "做",
    pinyin: "zuò",
    category: "Глаголы",
  },
  {
    russian: "Готовить еду",
    chinese: "做饭",
    pinyin: "zuòfàn",
    category: "Глаголы",
  },
  {
    russian: "Возвращаться",
    chinese: "回",
    pinyin: "huí",
    category: "Глаголы",
  },
  {
    russian: "Приходить (куда-то)",
    chinese: "来",
    pinyin: "lái",
    category: "Глаголы",
  },
  {
    russian: "Прибывать (куда-то)",
    chinese: "到",
    pinyin: "dào",
    category: "Глаголы",
  },
  {
    russian: "Мочь, иметь возможность",
    chinese: "能",
    pinyin: "néng",
    category: "Глаголы",
  },
  {
    russian: "Мочь, иметь возможность",
    chinese: "可以",
    pinyin: "kěyǐ",
    category: "Глаголы",
  },
  {
    russian: "Спать",
    chinese: "睡觉",
    pinyin: "shuìjiào",
    category: "Глаголы",
  },
  { russian: "Петь", chinese: "唱", pinyin: "chàng", category: "Глаголы" },
  {
    russian: "Танцевать",
    chinese: "跳舞",
    pinyin: "tiàowǔ",
    category: "Глаголы",
  },
  {
    russian: "Рисовать",
    chinese: "画画",
    pinyin: "huàhuà",
    category: "Глаголы",
  },
  {
    russian: "Кататься на лыжах",
    chinese: "滑雪",
    pinyin: "huáxuě",
    category: "Глаголы",
  },
  {
    russian: "Путешествовать",
    chinese: "旅游",
    pinyin: "lǚyóu",
    category: "Глаголы",
  },
  {
    russian: "Открывать, включать",
    chinese: "开",
    pinyin: "kāi",
    category: "Глаголы",
  },
  {
    russian: "Закрывать, выключать",
    chinese: "关",
    pinyin: "guān",
    category: "Глаголы",
  },
  { russian: "Помогать", chinese: "帮", pinyin: "bāng", category: "Глаголы" },
  { russian: "Ждать", chinese: "等", pinyin: "děng", category: "Глаголы" },
  { russian: "Искать", chinese: "找", pinyin: "zhǎo", category: "Глаголы" },
  {
    russian: "Сталкиваться (с кем-то)",
    chinese: "遇到",
    pinyin: "yùdào",
    category: "Глаголы",
  },
  {
    russian: "Заканчиваться",
    chinese: "结束",
    pinyin: "jiéshù",
    category: "Глаголы",
  },
  {
    russian: "Опаздывать",
    chinese: "迟到",
    pinyin: "chídào",
    category: "Глаголы",
  },
  {
    russian: "Начинаться",
    chinese: "开始",
    pinyin: "kāishǐ",
    category: "Глаголы",
  },
  {
    russian: "Убираться, чистить",
    chinese: "打扫",
    pinyin: "dǎsǎo",
    category: "Глаголы",
  },
  { russian: "Слушать", chinese: "听", pinyin: "tīng", category: "Глаголы" },
  {
    russian: "Слушаться",
    chinese: "听话",
    pinyin: "tīnghuà",
    category: "Глаголы",
  },
  { russian: "Играть", chinese: "玩", pinyin: "wán", category: "Глаголы" },
  {
    russian: "Сделать и получить результат (доделать)",
    chinese: "完",
    pinyin: "wán",
    category: "Глаголы",
  },
  {
    russian: "Серфить в интернете",
    chinese: "上网",
    pinyin: "shàngwǎng",
    category: "Глаголы",
  },
  {
    russian: "Надевать, носить (пальто, рубашку …)",
    chinese: "穿",
    pinyin: "chuān",
    category: "Глаголы",
  },
  {
    russian: "Надевать, носить (шапку, очки, перчатки)",
    chinese: "戴",
    pinyin: "dài",
    category: "Глаголы",
  },
  {
    russian: "Думать, полагать",
    chinese: "觉得",
    pinyin: "juédé",
    category: "Глаголы",
  },
  {
    russian: "Примерять (одежду)",
    chinese: "试",
    pinyin: "shì",
    category: "Глаголы",
  },
  {
    russian: "Попробовать (еду)",
    chinese: "尝",
    pinyin: "cháng",
    category: "Глаголы",
  },
  {
    russian: "Забронировать",
    chinese: "预订",
    pinyin: "yùdìng",
    category: "Глаголы",
  },
  {
    russian: "Использовать",
    chinese: "用",
    pinyin: "yòng",
    category: "Глаголы",
  },
  { russian: "Звонить", chinese: "打", pinyin: "dǎ", category: "Глаголы" },
  {
    russian: "Играть (в спорт руками)",
    chinese: "打",
    pinyin: "dǎ",
    category: "Глаголы",
  },
  {
    russian: "Уметь (иметь приобретенный навык)",
    chinese: "会",
    pinyin: "huì",
    category: "Глаголы",
  },
  { russian: "Пинать (мяч)", chinese: "踢", pinyin: "tī", category: "Глаголы" },
  { russian: "Кататься", chinese: "骑", pinyin: "qí", category: "Глаголы" },
  { russian: "Бегать", chinese: "跑步", pinyin: "pǎobù", category: "Глаголы" },
  { russian: "Гулять", chinese: "散步", pinyin: "sànbù", category: "Глаголы" },
  {
    russian: "Идти пешком",
    chinese: "走路",
    pinyin: "zǒulù",
    category: "Глаголы",
  },
  {
    russian: "Прогуливаться",
    chinese: "逛",
    pinyin: "guàng",
    category: "Глаголы",
  },
  {
    russian: "Плавать",
    chinese: "游泳",
    pinyin: "yóuyǒng",
    category: "Глаголы",
  },
  {
    russian: "Следует (должно, нужно)",
    chinese: "应该",
    pinyin: "yīnggāi",
    category: "Глаголы",
  },
  {
    russian: "Требуется",
    chinese: "需要",
    pinyin: "xūyào",
    category: "Глаголы",
  },
  {
    russian: "Не спать всю ночь",
    chinese: "熬夜",
    pinyin: "áoyè",
    category: "Глаголы",
  },
  {
    russian: "Ругаться",
    chinese: "吵架",
    pinyin: "chǎojià",
    category: "Глаголы",
  },
  {
    russian: "Расставаться",
    chinese: "分手",
    pinyin: "fēnshǒu",
    category: "Глаголы",
  },
  {
    russian: "Жениться",
    chinese: "结婚",
    pinyin: "jiéhūn",
    category: "Глаголы",
  },
  {
    russian: "Встретиться",
    chinese: "见面",
    pinyin: "jiànmiàn",
    category: "Глаголы",
  },
  {
    russian: "Пригласить, позаботиться",
    chinese: "请",
    pinyin: "qǐng",
    category: "Глаголы",
  },
  {
    russian: "Проводить, довезти",
    chinese: "送",
    pinyin: "sòng",
    category: "Глаголы",
  },
  { russian: "Дарить", chinese: "送", pinyin: "sòng", category: "Глаголы" },
  {
    russian: "Работать",
    chinese: "工作",
    pinyin: "gōngzuò",
    category: "Глаголы",
  },
  {
    russian: "Стать (кем-то)",
    chinese: "当",
    pinyin: "dāng",
    category: "Глаголы",
  },
  { russian: "Приносить", chinese: "拿", pinyin: "ná", category: "Глаголы" },
  {
    russian: "Совещаться",
    chinese: "开会",
    pinyin: "kāihuì",
    category: "Глаголы",
  },
  {
    russian: "Быть в командировке",
    chinese: "出差",
    pinyin: "chūchāi",
    category: "Глаголы",
  },
  {
    russian: "Распечатывать, печатать",
    chinese: "打印",
    pinyin: "dǎyìn",
    category: "Глаголы",
  },
  {
    russian: "Копировать, ксерокопировать",
    chinese: "复印",
    pinyin: "fùyìn",
    category: "Глаголы",
  },
  {
    russian: "Сидеть (ехать в транспорте)",
    chinese: "坐",
    pinyin: "zuò",
    category: "Глаголы",
  },
  {
    russian: "Вести машину",
    chinese: "开车",
    pinyin: "kāichē",
    category: "Глаголы",
  },
  { russian: "Отправлять", chinese: "发", pinyin: "fā", category: "Глаголы" },
  {
    russian: "Отвечать на звонок",
    chinese: "接",
    pinyin: "jiē",
    category: "Глаголы",
  },
  {
    russian: "Получать (сообщение)",
    chinese: "收",
    pinyin: "shōu",
    category: "Глаголы",
  },
  {
    russian: "Испытывать боль",
    chinese: "疼",
    pinyin: "téng",
    category: "Глаголы",
  },
  {
    russian: "Простужаться",
    chinese: "感冒",
    pinyin: "gǎnmào",
    category: "Глаголы",
  },
  {
    russian: "Температурить",
    chinese: "发烧",
    pinyin: "fāshāo",
    category: "Глаголы",
  },
  { russian: "Болеть", chinese: "病", pinyin: "bìng", category: "Глаголы" },
  {
    russian: "Болеть",
    chinese: "生病",
    pinyin: "shēngbìng",
    category: "Глаголы",
  },
  {
    russian: "Отдыхать",
    chinese: "休息",
    pinyin: "xiūxí",
    category: "Глаголы",
  },
  { russian: "Класть", chinese: "放", pinyin: "fàng", category: "Глаголы" },
  {
    russian: "Сделать что-то",
    chinese: "弄",
    pinyin: "nòng",
    category: "Глаголы",
  },
  { russian: "Портить", chinese: "坏", pinyin: "huài", category: "Глаголы" },
  { russian: "Терять", chinese: "丢", pinyin: "diū", category: "Глаголы" },
  {
    russian: "Знать (что-то)",
    chinese: "知道",
    pinyin: "zhīdào",
    category: "Глаголы",
  },
  {
    russian: "Знать (кого-то)",
    chinese: "认识",
    pinyin: "rènshì",
    category: "Глаголы",
  },
  { russian: "Ругать", chinese: "骂", pinyin: "mà", category: "Глаголы" },
  { russian: "Красть", chinese: "偷", pinyin: "tōu", category: "Глаголы" },
  { russian: "Врать", chinese: "骗", pinyin: "piàn", category: "Глаголы" },
  {
    russian: "Растить, иметь животное",
    chinese: "养",
    pinyin: "yǎng",
    category: "Глаголы",
  },
  {
    russian: "Решиться, дерзнуть",
    chinese: "敢",
    pinyin: "gǎn",
    category: "Глаголы",
  },
  { russian: "Писать", chinese: "写", pinyin: "xie", category: "Глаголы" },
  {
    russian: "Гладить (животное)",
    chinese: "摸",
    pinyin: "mō",
    category: "Глаголы",
  },
  {
    russian: "Выходить из дома",
    chinese: "出门",
    pinyin: "chūmén",
    category: "Глаголы",
  },
  {
    russian: "Составлять компанию",
    chinese: "陪",
    pinyin: "péi",
    category: "Глаголы",
  },
  { russian: "Кашлять", chinese: "咳嗽", pinyin: "késòu", category: "Глаголы" },
  {
    russian: "Давать разрешение, велеть",
    chinese: "让",
    pinyin: "ràng",
    category: "Глаголы",
  },
  {
    russian: "Делать укол",
    chinese: "打针",
    pinyin: "dǎzhēn",
    category: "Глаголы",
  },
  {
    russian: "Госпитализировать",
    chinese: "住院",
    pinyin: "zhùyuàn",
    category: "Глаголы",
  },
  {
    russian: "Заказывать (в ресторане)",
    chinese: "点菜",
    pinyin: "diǎncài",
    category: "Глаголы",
  },
  {
    russian: "Оплачивать счет (в ресторане)",
    chinese: "买单",
    pinyin: "mǎidān",
    category: "Глаголы",
  },
  {
    russian: "Забрать остатки",
    chinese: "打包",
    pinyin: "dǎbāo",
    category: "Глаголы",
  },
  { russian: "Повернуть", chinese: "拐", pinyin: "guǎi", category: "Глаголы" },
  {
    russian: "Тренироваться (заниматься фитнесом)",
    chinese: "健身",
    pinyin: "jiànshēn",
    category: "Глаголы",
  },

  { russian: "Писать", chinese: "写", pinyin: "xiě", category: "Глаголы" },
  {
    russian: "Фотографировать",
    chinese: "拍",
    pinyin: "pāi",
    category: "Глаголы",
  },
  {
    russian: "Переносить, передвигать (тяжелые объекты)",
    chinese: "搬",
    pinyin: "bān",
    category: "Глаголы",
  },
  {
    russian: "Менять, меняться",
    chinese: "换",
    pinyin: "huàn",
    category: "Глаголы",
  },
  { russian: "Выбирать", chinese: "挑", pinyin: "tiāo", category: "Глаголы" },
  {
    russian: "Решать, принять решение",
    chinese: "决定",
    pinyin: "juédìng",
    category: "Глаголы",
  },
  {
    russian: "Понимать",
    chinese: "了解",
    pinyin: "liǎojiě",
    category: "Глаголы",
  },
  {
    russian: "Учиться заграницей",
    chinese: "留学",
    pinyin: "liúxué",
    category: "Глаголы",
  },
  {
    russian: "Думать, полагать",
    chinese: "认为",
    pinyin: "rènwéi",
    category: "Глаголы",
  },
  { russian: "Читать", chinese: "读", pinyin: "dú", category: "Глаголы" },
  {
    russian: "Посещать (школу)",
    chinese: "上",
    pinyin: "shàng",
    category: "Глаголы",
  },
  {
    russian: "Должно, следует (время сделать …)",
    chinese: "该。。。了",
    pinyin: "gāi... le",
    category: "Глаголы",
  },
  {
    russian: "Сдавать экзамен",
    chinese: "考试",
    pinyin: "kǎoshì",
    category: "Глаголы",
  },
  {
    russian: "Выпуститься (из учебного заведения)",
    chinese: "毕业",
    pinyin: "bìyè",
    category: "Глаголы",
  },
  {
    russian: "Подготовиться (к экзамену)",
    chinese: "复习",
    pinyin: "fùxí",
    category: "Глаголы",
  },
  {
    russian: "Соглашаться",
    chinese: "同意",
    pinyin: "tóngyì",
    category: "Глаголы",
  },
  {
    russian: "Хотеть сделать что-то",
    chinese: "愿意",
    pinyin: "yuànyì",
    category: "Глаголы",
  },
  {
    russian: "Извиниться",
    chinese: "道歉",
    pinyin: "dàoqiàn",
    category: "Глаголы",
  },
  {
    russian: "Развестись",
    chinese: "离婚",
    pinyin: "líhūn",
    category: "Глаголы",
  },
  {
    russian: "Встречаться (иметь отношения)",
    chinese: "谈恋爱",
    pinyin: "tán liàn'ài",
    category: "Глаголы",
  },
  {
    russian: "Улыбаться, смеяться",
    chinese: "笑",
    pinyin: "xiào",
    category: "Глаголы",
  },
  { russian: "Плакать", chinese: "哭", pinyin: "kū", category: "Глаголы" },
  {
    russian: "Снять (одежду, обувь)",
    chinese: "脱",
    pinyin: "Tuō",
    category: "Глаголы",
  },
  {
    russian: "Выписывать из больницы",
    chinese: "出院",
    pinyin: "Chū yuàn",
    category: "Глаголы",
  },
  {
    russian: "Сойти (с самолета, поезда и т.д.)",
    chinese: "下",
    pinyin: "Xià",
    category: "Глаголы",
  },
  {
    russian: "Приземляться (о самолете)",
    chinese: "降落",
    pinyin: "Jiàngluò",
    category: "Глаголы",
  },
  {
    russian: "Взлетать (о самолете)",
    chinese: "起飞",
    pinyin: "Qǐfēi",
    category: "Глаголы",
  },
  {
    russian: "Предъявить",
    chinese: "出示",
    pinyin: "Chūshì",
    category: "Глаголы",
  },
  {
    russian: "Планировать",
    chinese: "打算",
    pinyin: "Dǎsuàn",
    category: "Глаголы",
  },
  {
    russian: "Планировать (составлять список задач на день)",
    chinese: "安排",
    pinyin: "Ānpái",
    category: "Глаголы",
  },
  {
    russian: "Долгосрочный план, программа",
    chinese: "计划",
    pinyin: "Jìhuà",
    category: "Глаголы",
  },
  {
    russian: "Подготовиться, быть готовым",
    chinese: "准备",
    pinyin: "Zhǔnbèi",
    category: "Глаголы",
  },
  {
    russian: "Уезжать за границу",
    chinese: "出国",
    pinyin: "Chūguó",
    category: "Глаголы",
  },
  {
    russian: "Подавать (заявление), обращаться (за документом)",
    chinese: "办",
    pinyin: "Bàn",
    category: "Глаголы",
  },
  {
    russian: "Выходить на контакт",
    chinese: "联系",
    pinyin: "Liánxì",
    category: "Глаголы",
  },
  {
    russian: "Отправлять что-то по почте",
    chinese: "寄",
    pinyin: "Jì",
    category: "Глаголы",
  },
  {
    russian: "Брать (с собой)",
    chinese: "带",
    pinyin: "Dài",
    category: "Глаголы",
  },
  {
    russian: "Надеяться",
    chinese: "希望",
    pinyin: "Xīwàng",
    category: "Глаголы",
  },
  {
    russian: "Уважать",
    chinese: "尊重",
    pinyin: "Zūnzhòng",
    category: "Глаголы",
  },
  {
    russian: "Заботиться",
    chinese: "关心",
    pinyin: "Guānxīn",
    category: "Глаголы",
  },
  { russian: "Жить", chinese: "住", pinyin: "Zhù", category: "Глаголы" },
  {
    russian: "Чистить (щеткой)",
    chinese: "刷",
    pinyin: "Shuā",
    category: "Глаголы",
  },
  { russian: "Спрашивать", chinese: "问", pinyin: "Wèn", category: "Глаголы" },
  { russian: "Понимать", chinese: "懂", pinyin: "Dǒng", category: "Глаголы" },
  {
    russian: "Радоваться, веселиться, быть в хорошем настроении",
    chinese: "快乐",
    pinyin: "Kuàilè",
    category: "Глаголы",
  },
  {
    russian: "Желать (хорошие пожелания)",
    chinese: "祝",
    pinyin: "Zhù",
    category: "Глаголы",
  },
  {
    russian: "Тошнить, рвать, блевать",
    chinese: "吐",
    pinyin: "Tǔ",
    category: "Глаголы",
  },
  {
    russian: "Настойчиво угощать вином, приглашать выпить",
    chinese: "劝酒",
    pinyin: "Quànjiǔ",
    category: "Глаголы",
  },
  {
    russian: "Наливать, опорожнять, опрокидывать, выгружать",
    chinese: "倒",
    pinyin: "Dào",
    category: "Глаголы",
  },
  {
    russian: "Продолжать(ся)",
    chinese: "继续",
    pinyin: "Jìxù",
    category: "Глаголы",
  },
  {
    russian: "Приглашать в гости",
    chinese: "请客",
    pinyin: "Qǐngkè",
    category: "Глаголы",
  },
  {
    russian: "Мыть (тереть, полировать)",
    chinese: "擦",
    pinyin: "Cā",
    category: "Глаголы",
  },
  { russian: "Бросать", chinese: "扔", pinyin: "Rēng", category: "Глаголы" },
  {
    russian: "Забыть",
    chinese: "忘记",
    pinyin: "wàngjì",
    category: "Глаголы",
  },
  {
    russian: "запомнить, помнить",
    chinese: "记",
    pinyin: "jì",
    category: "Глаголы",
  },
  {
    russian: "Запоминть, помнить",
    chinese: "记得",
    pinyin: "jìde",
    category: "Глаголы",
  },
  {
    russian: "думать (ошибочно полагать)",
    chinese: "以为",
    pinyin: "yǐwéi",
    category: "Глаголы",
  },
  {
    russian: "сообщить, сказать, проинформировать",
    chinese: "告诉",
    pinyin: "gàosu",
    category: "Глаголы",
  },
  {
    russian: "ненавидеть",
    chinese: "讨厌",
    pinyin: "tǎoyàn",
    category: "Глаголы",
  },
  {
    russian: "висеть",
    chinese: "挂",
    pinyin: "guà",
    category: "Глаголы",
  },
  {
    russian: "стоять",
    chinese: "站",
    pinyin: "zhàn",
    category: "Глаголы",
  },
  {
    russian: "отвечать",
    chinese: "回答",
    pinyin: "huídá",
    category: "Глаголы",
  },
  {
    russian: "представить(ся)",
    chinese: "介绍",
    pinyin: "jièshào",
    category: "Глаголы",
  },
  {
    russian: "уволиться",
    chinese: "辞职",
    pinyin: "cízhí",
    category: "Глаголы",
  },
  {
    russian: "получить повышение",
    chinese: "升职",
    pinyin: "shēngzhí",
    category: "Глаголы",
  },
  {
    russian: "увеличить",
    chinese: "涨",
    pinyin: "zhǎng",
    category: "Глаголы",
  },
  {
    russian: "должно, нужно",
    chinese: "得",
    pinyin: "děi",
    category: "Глаголы",
  },
  {
    russian: "перерабатывать (работать больше нормы)",
    chinese: "加班",
    pinyin: "jiābān",
    category: "Глаголы",
  },
  {
    russian: "отпроситься",
    chinese: "请假",
    pinyin: "qǐngjià",
    category: "Глаголы",
  },
  {
    russian: "заблудиться",
    chinese: "迷路",
    pinyin: "mílù",
    category: "Глаголы",
  },
  {
    russian: "израсходовать, потратить",
    chinese: "花",
    pinyin: "huā",
    category: "Глаголы",
  },
  {
    russian: "сломать (физически)",
    chinese: "破",
    pinyin: "pò",
    category: "Глаголы",
  },
  {
    russian: "сделать что-то до конца, без остатка (гл.модификатор)",
    chinese: "光",
    pinyin: "guāng",
    category: "Глаголы",
  },
  {
    russian: "видеть, встретить",
    chinese: "见",
    pinyin: "jiàn",
    category: "Глаголы",
  },
  {
    russian: "жить, поживать",
    chinese: "过",
    pinyin: "guò",
    category: "Глаголы",
  },
  {
    russian: "ошибаться",
    chinese: "错",
    pinyin: "cuò",
    category: "Глаголы",
  },
  {
    russian: "переехать",
    chinese: "搬家",
    pinyin: "bānjiā",
    category: "Глаголы",
  },
  {
    russian: "чувствовать себя",
    chinese: "感觉",
    pinyin: "gǎnjué",
    category: "Глаголы",
  },
  {
    russian: "учить (кого-то), обучать",
    chinese: "教",
    pinyin: "jiāo",
    category: "Глаголы",
  },
  {
    russian: "удивиться",
    chinese: "吃惊",
    pinyin: "chījīng",
    category: "Глаголы",
  },
  {
    russian: "выходить",
    chinese: "出",
    pinyin: "chū",
    category: "Глаголы",
  },
  {
    russian: "заходить",
    chinese: "进",
    pinyin: "jìn",
    category: "Глаголы",
  },
  {
    russian: "получить (что-то нематериальное)",
    chinese: "接受",
    pinyin: "jiēshòu",
    category: "Глаголы",
  },
  {
    russian: "Держать, сохранять",
    chinese: "保持",
    pinyin: "bǎochí",
    category: "Глаголы",
  },
  {
    russian: "сделать заказ (например, онлайн)",
    chinese: "下单",
    pinyin: "xiàdān",
    category: "Глаголы",
  },
  {
    russian: "Платить, оплачивать",
    chinese: "付款",
    pinyin: "fùkuǎn",
    category: "Глаголы",
  },
  {
    russian: "Возвращать",
    chinese: "退",
    pinyin: "tuì",
    category: "Глаголы",
  },
  {
    russian: "Иметь свободное время, быть свободным",
    chinese: "有空",
    pinyin: "yǒukòng",
    category: "Глаголы",
  },
  {
    russian: "Быть вместе, собираться, сходиться, встречаться",
    chinese: "聚会",
    pinyin: "jùhuì",
    category: "Глаголы",
  },
  {
    russian: "Тяжело трудиться, усердно работать",
    chinese: "辛苦",
    pinyin: "xīnkǔ",
    category: "Глаголы",
  },
  {
    russian: "Выиграть, одержать победу",
    chinese: "赢",
    pinyin: "yíng",
    category: "Глаголы",
  },
  {
    russian: "Добавлять, прибавлять",
    chinese: "加上",
    pinyin: "jiāshàng",
    category: "Глаголы",
  },
  {
    russian: "Сожалеть",
    chinese: "抱歉",
    pinyin: "bàoqiàn",
    category: "Глаголы",
  },
  {
    russian: "Отправляться",
    chinese: "出发",
    pinyin: "chūfā",
    category: "Глаголы",
  },
  {
    russian: "Нести яйца",
    chinese: "下蛋",
    pinyin: "xià dàn",
    category: "Глаголы",
  },
  {
    russian: "Говорят (по слухам)",
    chinese: "听说",
    pinyin: "tīngshuō",
    category: "Глаголы",
  },
  {
    russian: "Привыкнуть, адаптироваться",
    chinese: "习惯",
    pinyin: "xíguàn",
    category: "Глаголы",
  },
  {
    russian: "Изменить, модифицировать, отредактировать",
    chinese: "修改",
    pinyin: "xiūgǎi",
    category: "Глаголы",
  },
  {
    russian: "Уведомить, известить",
    chinese: "通知",
    pinyin: "tōngzhī",
    category: "Глаголы",
  },
  {
    russian: "Переводить, интерпретировать",
    chinese: "翻译",
    pinyin: "fānyì",
    category: "Глаголы",
  },
  {
    russian: "Обсуждать, дискутировать",
    chinese: "讨论",
    pinyin: "tǎolùn",
    category: "Глаголы",
  },
  {
    russian: "Обсуждать, дискутировать",
    chinese: "商量",
    pinyin: "shāngliáng",
    category: "Глаголы",
  },
  {
    russian: "Отказывать",
    chinese: "拒绝",
    pinyin: "jùjué",
    category: "Глаголы",
  },
  {
    russian: "Подписывать",
    chinese: "签",
    pinyin: "qiān",
    category: "Глаголы",
  },
  {
    russian: "Достигать",
    chinese: "得",
    pinyin: "dé",
    category: "Глаголы",
  },
  {
    russian: "Проиграть",
    chinese: "输",
    pinyin: "shū",
    category: "Глаголы",
  },
  {
    russian: "Поддерживать",
    chinese: "支持",
    pinyin: "zhīchí",
    category: "Глаголы",
  },
  {
    russian: "Опознавать, признавать, узнавать",
    chinese: "认出",
    pinyin: "rènchū",
    category: "Глаголы",
  },
  {
    russian: "Обращать внимание, принимать во внимание",
    chinese: "注意",
    pinyin: "zhùyì",
    category: "Глаголы",
  },
  {
    russian: "Быть гостем, гостить",
    chinese: "做客",
    pinyin: "zuòkè",
    category: "Глаголы",
  },
  {
    russian: "Стесняться, стыдиться",
    chinese: "害羞",
    pinyin: "hàixiū",
    category: "Глаголы",
  },
  {
    russian: "Тренироваться, практиковаться, упражняться",
    chinese: "练习",
    pinyin: "liànxí",
    category: "Глаголы",
  },
  {
    russian: "Одалживать, давать взаймы",
    chinese: "借",
    pinyin: "jiè",
    category: "Глаголы",
  },
  {
    russian: "Выбирать",
    chinese: "选择",
    pinyin: "xuǎnzé",
    category: "Глаголы",
  },
  {
    russian: "Лепить (снеговика)",
    chinese: "堆(雪人)",
    pinyin: "duī (xuěrén)",
    category: "Глаголы",
  },
  {
    russian: "Устать досмерти",
    chinese: "累死",
    pinyin: "lèisǐ",
    category: "Глаголы",
  },
  {
    russian: "Ходить пешком, ходьба",
    chinese: "步行",
    pinyin: "bùxíng",
    category: "Глаголы",
  },
  {
    russian: "Путешествовать",
    chinese: "旅行",
    pinyin: "lǚxíng",
    category: "Глаголы",
  },
  {
    russian: "Прощаться",
    chinese: "告别",
    pinyin: "gàobié",
    category: "Глаголы",
  },
  {
    russian: "Выступать с докладом, читать лекцию",
    chinese: "讲话",
    pinyin: "Jiǎnghuà",
    category: "Глаголы",
  },
  {
    russian: "Удерживать, упорно выполнять",
    chinese: "坚持",
    pinyin: "jiānchí",
    category: "Глаголы",
  },
  {
    russian: "Заниматься спортом",
    chinese: "运动",
    pinyin: "yùndòng",
    category: "Глаголы",
  },
  {
    russian: "Понимать",
    chinese: "明白",
    pinyin: "Míngbái",
    category: "Глаголы",
  },
  {
    russian: "Говорить (о чем-то)",
    chinese: "谈论",
    pinyin: "tánlùn",
    category: "Глаголы",
  },
  {
    russian: "Зайти, заехать (за кем-то)",
    chinese: "来接",
    pinyin: "Lái jiē",
    category: "Глаголы",
  },
  {
    russian: "Расти, взрослеть, становиться (каким-то)",
    chinese: "长",
    pinyin: "zhǎng",
    category: "Глаголы",
  },
  {
    russian: "Ехать / лететь в качестве пассажира",
    chinese: "乘坐",
    pinyin: "chéngzuò",
    category: "Глаголы",
  },
  {
    russian: "Сажать, сеять",
    chinese: "种",
    pinyin: "zhǒng",
    category: "Глаголы",
  },
  {
    russian: "Сдавать экзамен, познавать",
    chinese: "考",
    pinyin: "kǎo",
    category: "Глаголы",
  },
  {
    russian: "Начать занятие, приступить к учебе",
    chinese: "开学",
    pinyin: "kāixué",
    category: "Глаголы",
  },
  { russian: "Красить", chinese: "染", pinyin: "Rǎn", category: "Глаголы" },
  {
    russian: "Открыть (н-р, рот)",
    chinese: "张",
    pinyin: "zhāng",
    category: "Глаголы",
  },
  {
    russian: "Воспалиться",
    chinese: "发炎",
    pinyin: "fāyán",
    category: "Глаголы",
  },
  {
    russian: "Седеть",
    chinese: "变白",
    pinyin: "biàn bái",
    category: "Глаголы",
  },
  {
    russian: "Тянуть, тащить, трепать (языком)",
    chinese: "拉",
    pinyin: "lā",
    category: "Глаголы",
  },
  {
    russian: "Закапать (н-р, жидкое лекарство, капли)",
    chinese: "滴入",
    pinyin: "dīrù",
    category: "Глаголы",
  },
  {
    russian: "Замерзнуть, покрыться льдом, онеметь",
    chinese: "冻",
    pinyin: "dòng",
    category: "Глаголы",
  },
  {
    russian: "Жалеть, щадить",
    chinese: "惜",
    pinyin: "xī",
    category: "Глаголы",
  },
  { russian: "Терять", chinese: "失", pinyin: "shī", category: "Глаголы" },
  {
    russian: "Резать (ножницами), обрезать, стричь",
    chinese: "剪",
    pinyin: "jiǎn",
    category: "Глаголы",
  },
  {
    russian: "Делать педикюр",
    chinese: "修脚",
    pinyin: "xiūjiǎo",
    category: "Глаголы",
  },
  {
    russian: "Разорваться, лопнуть, треснуть",
    chinese: "裂",
    pinyin: "liè",
    category: "Глаголы",
  },
  {
    russian: "Нести на спине",
    chinese: "背着",
    pinyin: "bèizhe",
    category: "Глаголы",
  },
  {
    russian: "грызть, обгладывать",
    chinese: "肯",
    pinyin: "kěn",
    category: "Глаголы",
  },
  {
    russian: "показываться, появляться, выходить наружу",
    chinese: "露",
    pinyin: "lù， lòu",
    category: "Глаголы",
  },
  {
    russian: "заключить (договор)",
    chinese: "定",
    pinyin: "Dìng",
    category: "Глаголы",
  },
  { russian: "Дышать", chinese: "呼吸", pinyin: "Hūxī", category: "Глаголы" },
  {
    russian: "Сомневаться, относиться скептически",
    chinese: "怀疑",
    pinyin: "Huáiyí",
    category: "Глаголы",
  },
  {
    russian: "Беспокоить, напрягать, причинять неудобства",
    chinese: "麻烦",
    pinyin: "máfan",
    category: "Глаголы",
  },
  {
    russian: "ошибочно понять",
    chinese: "误会",
    pinyin: "wùhuì",
    category: "Глаголы",
  },
  {
    russian: "смеяться над кем-то, шутить",
    chinese: "笑话",
    pinyin: "xiàohuà",
    category: "Глаголы",
  },
  {
    russian: "Выйти (по направлению к говорящему)",
    chinese: "出来",
    pinyin: "Chūlái",
    category: "Глаголы",
  },
  {
    russian: "Выйти (по направлению от говорящего)",
    chinese: "出去",
    pinyin: "chūqù",
    category: "Глаголы",
  },
  {
    russian: "Зайти (по направлению к говорящему)",
    chinese: "进来",
    pinyin: "shūrù",
    category: "Глаголы",
  },
  {
    russian: "Зайти (по направлению от говорящего)",
    chinese: "进去",
    pinyin: "jìnqù",
    category: "Глаголы",
  },
  {
    russian: "Добраться (туда)",
    chinese: "过去",
    pinyin: "guòqù",
    category: "Глаголы",
  },
  {
    russian: "Добраться (сюда)",
    chinese: "过来",
    pinyin: "guòlái",
    category: "Глаголы",
  },
  {
    russian: "Подняться (по направлению к говорящему)",
    chinese: "上来",
    pinyin: "shànglái",
    category: "Глаголы",
  },
  {
    russian: "Спуститься (по направлению от говорящего)",
    chinese: "下去",
    pinyin: "xiàqù",
    category: "Глаголы",
  },
  {
    russian: "Прыгать, спрыгнуть",
    chinese: "跳",
    pinyin: "tiào",
    category: "Глаголы",
  },
  {
    russian: "Карабкаться, взбираться, ползти",
    chinese: "爬",
    pinyin: "pá",
    category: "Глаголы",
  },
  {
    russian: "Зарабатывать, делать деньги",
    chinese: "赚",
    pinyin: "Zhuàn",
    category: "Глаголы",
  },
  {
    russian: "Копить, класть на депозит",
    chinese: "存",
    pinyin: "cún",
    category: "Глаголы",
  },
  {
    russian: "Обдумывать, вникать, размышлять",
    chinese: "考虑",
    pinyin: "kǎolǜ",
    category: "Глаголы",
  },
  {
    russian: "Курить",
    chinese: "抽烟",
    pinyin: "Chōuyān",
    category: "Глаголы",
  },
  {
    russian: "Критиковать",
    chinese: "批评",
    pinyin: "pīpíng",
    category: "Глаголы",
  },
  {
    russian: "Обещать",
    chinese: "答应",
    pinyin: "chéngnuò",
    category: "Глаголы",
  },
  {
    russian: "Напоминать",
    chinese: "提醒",
    pinyin: "tíxǐng",
    category: "Глаголы",
  },
  {
    russian: "Прощать",
    chinese: "原谅",
    pinyin: "yuánliàng",
    category: "Глаголы",
  },
  {
    russian: "Признавать (н-р, ошибку), соглашаться",
    chinese: "承认",
    pinyin: "chéngrèn",
    category: "Глаголы",
  },
  { russian: "Объяснять", chinese: "讲", pinyin: "jiǎng", category: "Глаголы" },
  {
    russian: "Объяснять",
    chinese: "解释",
    pinyin: "jiěshì",
    category: "Глаголы",
  },
  {
    russian: "Принимать участие (в мероприятии)",
    chinese: "参加",
    pinyin: "Cānjiā",
    category: "Глаголы",
  },
  {
    russian: "Интересоваться",
    chinese: "感兴趣",
    pinyin: "gǎn xìngqù",
    category: "Глаголы",
  },
  {
    russian: "Быть в курсе, хорошо знать, быть знакомым с…",
    chinese: "熟悉",
    pinyin: "shúxī",
    category: "Глаголы",
  },
  {
    russian: "Относиться серьезно, принимать всерьез",
    chinese: "重视",
    pinyin: "zhòngshì",
    category: "Глаголы",
  },
  {
    russian: "Врать",
    chinese: "说谎",
    pinyin: "Shuōhuǎng",
    category: "Глаголы",
  },
  {
    russian: "Совершать (ошибку, преступление)",
    chinese: "犯",
    pinyin: "fàn",
    category: "Глаголы",
  },
  {
    russian: "Сдаваться",
    chinese: "放弃",
    pinyin: "fàngqì",
    category: "Глаголы",
  },
  {
    russian: "Решать (проблему)",
    chinese: "解决",
    pinyin: "jiějué",
    category: "Глаголы",
  },
  {
    russian: "Худеть, терять вес",
    chinese: "减肥",
    pinyin: "jiǎnféi",
    category: "Глаголы",
  },
];

export { wordListVerbs };
